Repository hmcts/adoption-web, pull requests merged in 2021-12, with the labels that each got.

#50 Adop 128 taskpage
  src/main/app/case/case.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/task-list.scss
  src/main/routes.ts
  src/main/steps/applicant1/applying-with/content.ts
  src/main/steps/applicant1/date-child-moved-in/content.ts
  src/main/steps/applicant1/your-contact-details/content.ts
  src/main/steps/applicant1/your-identity-documents/content.ts
  src/main/steps/applicant1/your-personal-details/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/form/form.njk
  src/main/steps/eligibility/start-eligibility/content.ts
  src/main/steps/index.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/get.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-50

#52 fixed common template title issue
  src/main/steps/applicant1/applying-with/content.ts
  src/main/steps/common/form/fields/radios.njk
  src/main/steps/common/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-52

#53 improved step url logic
  src/main/steps/index.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/task-list/content.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/timed-out/get.test.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-53

#55 Adop 101 eligibility
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/modules/oidc/index.ts
  src/main/server.ts
  src/main/steps/common/common.content.ts
  src/main/steps/eligibility/EligibilityPostController.ts
  src/main/steps/eligibility/cannot-apply/content.ts
  src/main/steps/eligibility/cannot-apply/post.ts
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/eligibility/married/post.ts
  src/main/steps/eligibility/routes.ts
  src/main/steps/eligibility/start-eligibility/get.ts
  src/main/steps/eligibility/start/content.ts
  src/main/steps/eligibility/start/template.njk
  src/main/steps/eligibility/under-18/content.test.ts
  src/main/steps/eligibility/under-18/content.ts
  src/main/steps/eligibility/under-18/post.ts
  src/main/steps/eligibilitySequence.test.ts
  src/main/steps/eligibilitySequence.ts
  src/main/steps/index.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-55

#57 E2E test for Child Eligibility
  Jenkinsfile_nightly
  codecept.conf.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/taskList_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-57

#54 Primary applicant contact details
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  codecept.conf.js
  config/default.yaml
  jest.config.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/app/keepalive/KeepAliveController.test.ts
  src/main/app/keepalive/KeepAliveController.ts
  src/main/app/postcode/postcode-lookup-api.test.ts
  src/main/app/postcode/postcode-lookup-api.ts
  src/main/assets/js/session-timeout.ts
  src/main/assets/scss/main.scss
  src/main/modules/i18n/index.test.ts
  src/main/modules/i18n/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.test.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/applicant1/applying-with/content.test.ts
  src/main/steps/applicant1/applying-with/content.ts
  src/main/steps/applicant1/contact-details/content.test.ts
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/applicant1/find-address/content.test.ts
  src/main/steps/applicant1/find-address/content.ts
  src/main/steps/applicant1/find-address/form.njk
  src/main/steps/applicant1/find-address/post.test.ts
  src/main/steps/applicant1/find-address/post.ts
  src/main/steps/applicant1/find-address/template.njk
  src/main/steps/applicant1/manual-address/content.test.ts
  src/main/steps/applicant1/manual-address/content.ts
  src/main/steps/applicant1/select-address/content.test.ts
  src/main/steps/applicant1/select-address/content.ts
  src/main/steps/applicant1/select-address/form.njk
  src/main/steps/applicant1/select-address/post.test.ts
  src/main/steps/applicant1/select-address/post.ts
  src/main/steps/applicant1/select-address/template.njk
  src/main/steps/applicant1/your-contact-details/content.ts
  src/main/steps/applicant1Sequence.test.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields/select.njk
  src/main/steps/common/form/form.njk
  src/main/steps/index.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
  src/test/unit/utils/mockPostcodeResponses.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-54

#62 Fee integration
  config/default.yaml
  jest.config.js
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/fee/fee-lookup-api.ts
  src/main/steps/applicant1/fee-lookup/content.ts
  src/main/steps/applicant1/fee-lookup/get.ts
  src/main/steps/applicant1Sequence.test.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-62

#63 removed unused files
  src/main/steps/applicant1/date-from-certificate/content.ts
  src/main/steps/applicant1/how-to-apply-financial-order/content.ts
  src/main/steps/applicant1/how-to-apply-financial-order/template.njk
  src/main/steps/applicant1/irretrievable-breakdown/content.ts
  src/main/steps/applicant1/not-long-enough-to-apply/content.ts
  src/main/steps/applicant1/not-long-enough-to-apply/template.njk
  src/main/steps/applicant1/relationship-not-broken/content.ts
  src/main/steps/applicant1/relationship-not-broken/template.njk
  src/main/steps/index.test.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-63

#64 Adop 207 child placement order
  codecept.conf.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/placement-order-court/content.test.ts
  src/main/steps/children/placement-order-court/content.ts
  src/main/steps/children/placement-order-court/get.test.ts
  src/main/steps/children/placement-order-court/get.ts
  src/main/steps/children/placement-order-court/post.test.ts
  src/main/steps/children/placement-order-court/post.ts
  src/main/steps/children/placement-order-number/content.test.ts
  src/main/steps/children/placement-order-number/content.ts
  src/main/steps/children/placement-order-number/get.test.ts
  src/main/steps/children/placement-order-number/get.ts
  src/main/steps/children/placement-order-number/post.test.ts
  src/main/steps/children/placement-order-number/post.ts
  src/main/steps/children/placement-order/get.test.ts
  src/main/steps/children/placement-order/get.ts
  src/main/steps/children/placement-order/post.test.ts
  src/main/steps/children/placement-order/post.ts
  src/main/steps/common/form/fields/date.njk
  src/main/steps/common/form/fields/input.njk
  src/main/steps/index.ts
  src/main/steps/task-list/template.njk
  src/main/steps/urls.ts
  src/test/e2e/actors/base.js
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-64

#65 ADOP-205 full name and dob screen change
  codecept.conf.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/date-of-birth/content.test.ts
  src/main/steps/children/date-of-birth/content.ts
  src/main/steps/children/full-name/content.test.ts
  src/main/steps/children/full-name/content.ts
  src/main/steps/children/sex-at-birth/content.test.ts
  src/main/steps/children/sex-at-birth/content.ts
  src/main/steps/common/page.njk
  src/main/steps/common/template.njk
  src/main/steps/task-list/template.njk
  src/main/steps/urls.ts
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-65

#67 Adop 207 child placement order
  src/main/app/case/case.ts
  src/main/app/form/validation.test.ts
  src/main/assets/scss/main.scss
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/date-of-birth/content.test.ts
  src/main/steps/children/date-of-birth/content.ts
  src/main/steps/children/placement-order-date/content.test.ts
  src/main/steps/children/placement-order-date/content.ts
  src/main/steps/children/placement-order-date/get.test.ts
  src/main/steps/children/placement-order-date/get.ts
  src/main/steps/children/placement-order-date/post.test.ts
  src/main/steps/children/placement-order-date/post.ts
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/content.ts
  src/main/steps/children/placement-order-summary/form.njk
  src/main/steps/children/placement-order-summary/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields/radios.njk
  src/main/steps/urls.ts
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-67

#61 Adop 125 primary applicant personal details
  .gitignore
  codecept.conf.js
  jest.config.js
  package.json
  src/main/app/case/case.ts
  src/main/app/controller/GetController.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/applicant1/dob/content.test.ts
  src/main/steps/applicant1/dob/content.ts
  src/main/steps/applicant1/full-name/content.test.ts
  src/main/steps/applicant1/full-name/content.ts
  src/main/steps/applicant1/nationality/content.test.ts
  src/main/steps/applicant1/nationality/content.ts
  src/main/steps/applicant1/nationality/get.ts
  src/main/steps/applicant1/nationality/post.ts
  src/main/steps/applicant1/occupation/content.test.ts
  src/main/steps/applicant1/occupation/content.ts
  src/main/steps/applicant1/occupation/form.njk
  src/main/steps/applicant1/occupation/template.njk
  src/main/steps/applicant1/other-names/content.test.ts
  src/main/steps/applicant1/other-names/content.ts
  src/main/steps/applicant1/other-names/get.ts
  src/main/steps/applicant1/other-names/post.test.ts
  src/main/steps/applicant1/other-names/post.ts
  src/main/steps/applicant1/your-personal-details/content.ts
  src/main/steps/applicant1Sequence.test.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/form/fields/button.njk
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/common/form/fields/details.njk
  src/main/steps/common/form/fields/summarylist.njk
  src/main/steps/common/functions/mapSummaryListContent.ts
  src/main/steps/common/models/summaryListContent.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
  test-results/result.xml
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-61

#69 Adop 206 certificate details
  jest.config.js
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/full-name-after-adoption/content.test.ts
  src/main/steps/children/full-name-after-adoption/content.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-69

#70 Error message updated as per UCD prototype.
  src/main/steps/eligibility/lived-uk/content.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/eligibility/under-18/content.ts
  src/main/steps/eligibility/under-21/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-70
