Repository hmcts/adoption-web, pull requests merged in 2021-11, with the labels that each got.

#29 Lint config changes
  .eslintrc.js
  Dockerfile
  codecept.conf.js
  docker-compose.yml
  nodemon.json
  src/main/app.ts
  src/main/development.ts
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/health.ts
  src/main/routes/info.ts
  src/main/server.ts
  src/main/views/home.njk
  src/test/a11y/a11y.ts
  src/test/e2e/actors/base.js
  src/test/e2e/actors/tabs.js
  src/test/e2e/config.js
  src/test/e2e/helpers/dump_browser_logs_helper.js
  src/test/e2e/helpers/hooks_helper.js
  src/test/e2e/helpers/stepListener.js
  src/test/e2e/pages/caseList.page.js
  src/test/e2e/pages/eventSummary.page.js
  src/test/e2e/pages/events/openApplicationEvent.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/reporters/json-file-reporter/report-aggregator.js
  src/test/e2e/reporters/json-file-reporter/report-aggregator.test.js
  src/test/e2e/reporters/json-file-reporter/reporter.js
  src/test/e2e/reporters/json-file-reporter/utils.js
  webpack.config.js
  webpack/app.js
  webpack/govukFrontend.js
  webpack/htmlWebpack.js
  webpack/scss.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-29

#30 added keyvault config in Jenkinsfile, charts and infrastructure
  Jenkinsfile_CNP
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
  src/main/modules/properties-volume/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-30

#33 E2E for Login and Landing Page
  Jenkinsfile_CNP
  codecept.conf.js
  src/test/e2e/actors/base.js
  src/test/e2e/config.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/login.page.js
  src/test/tests/smoke_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-33

#38 Revert "using usePodIdentity: true in charts"
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-38

#41 AAT smoke test config
  Jenkinsfile_CNP
  src/test/e2e/config.js
  src/test/tests/smoke_test.js
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-41

#44 added s2s secret copy terraform code
  infrastructure/main.tf
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-44

#42 "ADOP-113-header updated header for all pages"
  Jenkinsfile_CNP
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/routes.test.ts
  src/main/server.ts
  src/main/steps/applicant1/number-of-children/content.ts
  src/main/steps/applicant1/number-of-children/template.njk
  src/main/steps/applicant1/your-details/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/form.njk
  src/main/steps/common/page.njk
  src/main/steps/eligibility/routes.ts
  src/main/steps/eligibility/start-eligibility/content.ts
  src/main/steps/eligibility/start-eligibility/get.ts
  src/main/steps/eligibility/start-eligibility/template.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/urls.ts
  src/test/config.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-42

#49 added logic to display field error even if there is only one field
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes.test.ts
  src/main/steps/applicant1/applying-with/content.ts
  src/main/steps/applicant1/applying-with/template.njk
  src/main/steps/applicant1/date-from-certificate/content.ts
  src/main/steps/applicant1/how-to-apply-financial-order/content.ts
  src/main/steps/applicant1/irretrievable-breakdown/content.ts
  src/main/steps/applicant1/number-of-children/content.ts
  src/main/steps/applicant1/number-of-children/template.njk
  src/main/steps/applicant1/your-names-on-certificate/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields/radios.njk
  src/main/steps/common/form/form.njk
  src/main/steps/common/template.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/urls.ts
  src/test/config.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  src/test/tests/smoke_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-49
