Repository hmcts/adoption-web, pull requests merged in 2022-02, with the labels that each got.

#182 PCQ change
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/review-pay-submit/equality/PcqParameters.ts
  src/main/steps/review-pay-submit/equality/content.ts
  src/main/steps/review-pay-submit/equality/createToken.test.ts
  src/main/steps/review-pay-submit/equality/createToken.ts
  src/main/steps/review-pay-submit/equality/get.test.ts
  src/main/steps/review-pay-submit/equality/get.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts
  src/main/steps/task-list/content.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-182

#183 Adop 155 payment end 2 end
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  codecept.conf.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/fee/fee-lookup-api.test.ts
  src/main/app/fee/fee-lookup-api.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/payment/PaymentModel.test.ts
  src/main/app/payment/PaymentModel.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/form.njk
  src/main/steps/review-pay-submit/check-your-answers/template.njk
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/utils.ts
  src/test/e2e/helpers/hooks_helper.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/tests/applicantDetails_test.js
  src/test/e2e/tests/childDetails_test.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/otherApplicantDetails_test.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/e2e/tests/taskList_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-183

#187 whitlelisted oauth cookie
  Jenkinsfile_CNP
  src/main/assets/js/cookie.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-187

#189 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-189

#190 Adop 359 additional sibling and placement orders
  package.json
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/assets/scss/main.scss
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.test.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.ts
  src/main/steps/sibling/name/SiblingGetController.test.ts
  src/main/steps/sibling/name/SiblingGetController.ts
  src/main/steps/sibling/name/SiblingPostController.test.ts
  src/main/steps/sibling/name/SiblingPostController.ts
  src/main/steps/sibling/placement-order-type/content.test.ts
  src/main/steps/sibling/placement-order/get.ts
  src/main/steps/sibling/select-sibling/SelectSiblingPostController.ts
  src/main/steps/sibling/select-sibling/content.test.ts
  src/main/steps/sibling/select-sibling/content.ts
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
  src/main/steps/sibling/summary/content.ts
  src/main/steps/sibling/summary/form.njk
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childSiblingDetails.page.js
  src/test/unit/utils/languageAssertions.ts
  yarn-audit-issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-190

#191 Adop-19 change
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/birth-father/address-known/content.test.ts
  src/main/steps/birth-father/address-known/content.ts
  src/main/steps/birth-mother/address-known/content.test.ts
  src/main/steps/birth-mother/address-known/content.ts
  src/main/steps/other-parent/address-known/content.test.ts
  src/main/steps/other-parent/address-known/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-191

#193 Adop 359 change sibling po
  src/main/app/controller/PostController.ts
  src/main/steps/sibling/name/SiblingPostController.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.test.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.ts
  src/main/steps/sibling/placement-order-check-your-answers/form.njk
  src/main/steps/sibling/placement-order-check-your-answers/get.test.ts
  src/main/steps/sibling/placement-order-check-your-answers/get.ts
  src/main/steps/sibling/placement-order-check-your-answers/template.njk
  src/main/steps/sibling/placement-order/get.ts
  src/main/steps/sibling/placement-order/post.ts
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
  src/main/steps/sibling/summary/content.ts
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-193

#196 Adop app insights
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.yaml
  src/main/modules/properties-volume/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-196

#199 Add Dependency to audit file
  src/test/e2e/helpers/hooks_helper.js
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-199

#202 Add Dependency to audit file
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-202

#198 Adop 352 remove sibling po
  charts/adoption-web/Chart.yaml
  src/main/steps/sibling/name/SiblingPostController.ts
  src/main/steps/sibling/placement-order/get.test.ts
  src/main/steps/sibling/placement-order/get.ts
  src/main/steps/sibling/remove-placement-order/SiblingRemovePlacementOrderPostController.test.ts
  src/main/steps/sibling/remove-placement-order/SiblingRemovePlacementOrderPostController.ts
  src/main/steps/sibling/remove-placement-order/content.test.ts
  src/main/steps/sibling/remove-placement-order/content.ts
  src/main/steps/sibling/remove-placement-order/get.test.ts
  src/main/steps/sibling/remove-placement-order/get.ts
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-198

#197 Fortify Added
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/config/gradlew.bat
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/settings.gradle
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-197

#203 fixed bug related to empty sibling name
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-203

#205 updated content for eligibility -> married screen
  src/main/steps/eligibility/constants.ts
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-205

#206 Added consent to contact details
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/address/lookup/content.test.ts
  src/main/steps/applicant1/address/lookup/content.ts
  src/main/steps/applicant1/address/manual/content.test.ts
  src/main/steps/applicant1/address/manual/content.ts
  src/main/steps/applicant1/address/select/content.test.ts
  src/main/steps/applicant1/address/select/content.ts
  src/main/steps/applicant1/contact-details/content.test.ts
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/applicant2/contact-details/content.test.ts
  src/main/steps/applicant2/contact-details/content.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/test/e2e/pages/otherApplicant.page.js
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-206

#209 added other names text and unit tests
  src/main/steps/applicant1/other-names/content.test.ts
  src/main/steps/applicant1/other-names/content.ts
  src/main/steps/common/components/other-names.test.ts
  src/main/steps/common/components/other-names.ts
  src/main/steps/common/form/fields/label.njk
  src/test/e2e/pages/reviewPayAndSubmit.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-209

#214 ADOP-607
  charts/adoption-web/values.preview.template.yaml
  config/custom-environment-variables.yaml
  src/main/steps/review-pay-submit/equality/get.test.ts
  src/main/steps/review-pay-submit/equality/get.ts
  src/test/e2e/pages/reviewPayAndSubmit.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-214

#212 Removed Nationality for Applicant1 & Applicant2
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/nationality/NationalityGetController.test.ts
  src/main/app/nationality/NationalityPostController.test.ts
  src/main/steps/applicant1/applicant1Sequence.test.ts
  src/main/steps/applicant1/applicant1Sequence.ts
  src/main/steps/applicant1/nationality/NationalityGetController.test.ts
  src/main/steps/applicant1/nationality/NationalityGetController.ts
  src/main/steps/applicant1/nationality/NationalityPostController.test.ts
  src/main/steps/applicant1/nationality/NationalityPostController.ts
  src/main/steps/applicant1/nationality/content.test.ts
  src/main/steps/applicant1/nationality/content.ts
  src/main/steps/applicant2/applicant2Sequence.test.ts
  src/main/steps/applicant2/applicant2Sequence.ts
  src/main/steps/applicant2/nationality/NationalityGetController.test.ts
  src/main/steps/applicant2/nationality/NationalityGetController.ts
  src/main/steps/applicant2/nationality/NationalityPostController.test.ts
  src/main/steps/applicant2/nationality/NationalityPostController.ts
  src/main/steps/applicant2/nationality/content.test.ts
  src/main/steps/applicant2/nationality/content.ts
  src/main/steps/common/components/nationality.test.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-212

#216 ADOP- 607
  charts/adoption-web/values.preview.template.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-216

#211 ADOP 555 change
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/uploaded-files.ts
  src/main/app/case/to-api-format.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/form/validation.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/steps/applicant1/address/lookup/content.test.ts
  src/main/steps/applicant1/address/lookup/content.ts
  src/main/steps/applicant1/address/manual/content.test.ts
  src/main/steps/applicant1/address/manual/content.ts
  src/main/steps/applicant1/address/select/content.test.ts
  src/main/steps/applicant1/address/select/content.ts
  src/main/steps/applicant1/applying-with/content.test.ts
  src/main/steps/applicant1/applying-with/content.ts
  src/main/steps/applicant1/applying-with/template.njk
  src/main/steps/applicant1/dob/content.test.ts
  src/main/steps/applicant1/dob/content.ts
  src/main/steps/applicant1/full-name/content.test.ts
  src/main/steps/applicant1/full-name/content.ts
  src/main/steps/applicant1/occupation/content.test.ts
  src/main/steps/applicant1/occupation/content.ts
  src/main/steps/applicant1/upload-your-documents/content.test.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/common/components/address-lookup.test.ts
  src/main/steps/common/components/address-lookup.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/address-manual.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/address-select.ts
  src/main/steps/home/get.test.ts
  src/main/steps/index.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-211
