Repository hmcts/adoption-web, pull requests merged in 2022-10, with the labels that each got.

#815 ADOP-REDIS-ISUE: Redis document upload issue fix
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/draft-store/draft-store-service.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-815

#818 Elastic search enable
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/CaseApi.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-818

#817 Enable PACT Tests
  Jenkinsfile_CNP
  src/test/pact/ccd-data-store-api.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-817

#816 ADOP-1415-LAPortal-Docmosis
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-816

#808 ADOP-348 payment tab changes
  src/main/app/payment/PaymentModel.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-808

#830 Upload Document name issue fix
  src/main/steps/la-portal/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-830

#840 Removing additional call to ref-data-api
  src/main/app/court/court-venues-api.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-840

#847 fix: Demo-Environment-Fix
  src/main/app/case/definition.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-847

#857 Fix sonar issues in adoption-web
  src/main/steps/application/task-list/utils.ts
  src/main/steps/sibling/placement-order/get.ts
  src/main/steps/sibling/relation/SiblingGetController.ts
  src/main/steps/sibling/relation/SiblingPostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-857
