Repository hmcts/adoption-web, pull requests merged in 2022-05, with the labels that each got.

#405 Adop 889 pact verification
  Jenkinsfile_CNP
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app/auth/user/oidc.ts
  src/main/app/payment/PaymentClient.ts
  src/test/pact/dm-store.test.ts
  src/test/pact/idam-api.test.ts
  src/test/pact/payment-api.test.ts
  src/test/pact/publish/ca-bundle.crt
  src/test/pact/publish/publish.ts
  src/test/pact/rpe-service-auth-provider.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-405

#408 Adop 907 content update
  src/main/steps/applicant1/applying-with/content.test.ts
  src/main/steps/applicant1/applying-with/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-408

#407 ADOP-697 cancel payment redirect
  src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-407

#354 Adop 820 analytics
  src/main/modules/helmet/index.ts
  src/main/steps/common/page.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-354

#412 bumped packages as per dependabot recommendation
  package.json
  src/main/server.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-412

#454 fix pact test issue related to jest 28.x
  bin/remove-stuck-pr.sh
  jest.pact.config.js
  src/test/pact/ccd-data-store-api.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-454

#453 Adop 795 local authority changes
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyGetController.test.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyGetController.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyPostController.test.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyPostController.ts
  src/main/steps/children/adoption-agency/content.test.ts
  src/main/steps/children/adoption-agency/content.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/local-authority/content.test.ts
  src/main/steps/children/local-authority/content.ts
  src/main/steps/children/other-adoption-agency/content.test.ts
  src/main/steps/children/other-adoption-agency/content.ts
  src/main/steps/children/social-worker/content.test.ts
  src/main/steps/children/social-worker/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
  src/main/steps/task-list/content.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/otherApplicant.page.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-453

#464 fixed issue with wrong tag
  src/main/steps/common/page.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-464

#458 E2 e negative
  src/test/config.ts
  src/test/e2e/fixtures/caseData/childAdoptionAgencyDetails.js
  src/test/e2e/fixtures/caseData/childAdoptionCertificateDetails.js
  src/test/e2e/fixtures/caseData/childBirthFatherDetails.js
  src/test/e2e/fixtures/caseData/childBirthMothersDetails.js
  src/test/e2e/fixtures/caseData/childDetailsPlacementOrder.js
  src/test/e2e/fixtures/caseData/childOtherParentDetails.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/childAdoptionCertificateDetails.page.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/e2e/pages/childBirthMothersDetails.page.js
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/dateChildMovedinDetails.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/pages/uploadDocumentsDetails.page.js
  src/test/e2e/tests/e2enegative_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-458

#481 upgrading to redis_version 6 in terraform
  infrastructure/main.tf
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-481

#489 Adop 945 task list changes
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/find-family-court/content.test.ts
  src/main/steps/children/find-family-court/content.ts
  src/main/steps/children/find-placement-order-court/content.test.ts
  src/main/steps/children/find-placement-order-court/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
  src/main/steps/task-list/content.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/chooseYourFamilyCourtDetails.page.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-489

#501 Stopping fortify until false positive issue is fixed.
  Jenkinsfile_nightly
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-501

#505 Bugfix family court name
  src/main/steps/children/find-family-court/FindFamilyCourtPostController.test.ts
  src/main/steps/children/find-family-court/FindFamilyCourtPostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-505

#511 Update Browser version
  src/test/e2e/crossbrowser/supportedBrowsers.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-511

#510 downmerge master changes into R2master
  Jenkinsfile_nightly
  charts/adoption-web/Chart.yaml
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-510
