Repository hmcts/adoption-web, pull requests merged in 2022-11, with the labels that each got.

#863 Sonar issues fixes
  src/main/app/controller/PostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-863

#856 Adop 1679 enabling pact
  src/test/pact/ccd-data-store-api.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-856

#867 Major sonar fixes
  src/main/steps/la-portal/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-867

#868 CUI Negative test case
  src/test/e2e/fixtures/caseData/applicantOrYourSocialWorkerDetails.js
  src/test/e2e/fixtures/caseData/childAdoptionAgencyDetails.js
  src/test/e2e/fixtures/caseData/childBasicDetails.js
  src/test/e2e/fixtures/caseData/childSocialWorkerDetails.js
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/childsDetails.page.js
  src/test/e2e/pages/chooseYourFamilyCourtDetails.page.js
  src/test/e2e/pages/dateChildMovedinDetails.page.js
  src/test/e2e/pages/otherApplicant.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/tests/e2enegative_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-868

#859 enabling trigger word search for courts
  src/main/steps/children/find-family-court/util.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-859

#875 Fixed FPET-259 Moved the test data to test.yml
  config/test.yaml
  src/main/app/auth/user/oidc.integration.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-875

#869 Acceptability changes
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/applicant1/date-child-moved-in/content.test.ts
  src/main/steps/applicant1/date-child-moved-in/content.ts
  src/main/steps/applicant1/dob/content.test.ts
  src/main/steps/applicant1/dob/content.ts
  src/main/steps/applicant2/dob/content.test.ts
  src/main/steps/applicant2/dob/content.ts
  src/main/steps/birth-father/address-known/content.test.ts
  src/main/steps/birth-father/address-known/content.ts
  src/main/steps/birth-father/alive/content.test.ts
  src/main/steps/birth-father/alive/content.ts
  src/main/steps/birth-father/last-address-confirmed/content.test.ts
  src/main/steps/birth-father/last-address-confirmed/content.ts
  src/main/steps/birth-father/name-on-certificate/content.test.ts
  src/main/steps/birth-father/name-on-certificate/content.ts
  src/main/steps/birth-mother/last-address-confirmed/content.test.ts
  src/main/steps/birth-mother/last-address-confirmed/content.ts
  src/main/steps/birth-mother/still-alive/content.test.ts
  src/main/steps/birth-mother/still-alive/content.ts
  src/main/steps/children/date-of-birth/content.test.ts
  src/main/steps/children/date-of-birth/content.ts
  src/main/steps/children/placement-order-date/content.test.ts
  src/main/steps/children/placement-order-date/content.ts
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/content.ts
  src/main/steps/common/components/nationality.test.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/la-portal/kba-case-ref/content.test.ts
  src/main/steps/la-portal/kba-case-ref/content.ts
  src/main/steps/other-parent/address-known/content.test.ts
  src/main/steps/other-parent/address-known/content.ts
  src/main/steps/other-parent/exists/content.test.ts
  src/main/steps/other-parent/exists/content.ts
  src/main/steps/other-parent/last-address-confirmed/content.test.ts
  src/main/steps/other-parent/last-address-confirmed/content.ts
  src/main/steps/sibling/exists/content.test.ts
  src/main/steps/sibling/exists/content.ts
  src/main/steps/sibling/placement-order-number/content.test.ts
  src/main/steps/sibling/placement-order-number/content.ts
  src/main/steps/sibling/placement-order-type/content.test.ts
  src/main/steps/sibling/placement-order-type/content.ts
  src/main/steps/sibling/relation/content.test.ts
  src/main/steps/sibling/relation/content.ts
  src/main/steps/sibling/summary/content.test.ts
  src/main/steps/sibling/summary/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-869

#880 Updating terraform version
  infrastructure/.terraform-version
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-880

#885 Fixed Document Upload Issue
  src/main/steps/la-portal/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-885

#892 ADOP-1876-Defect-LabelNationality
  src/main/steps/common/components/nationality.test.ts
  src/main/steps/common/components/nationality.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-892
