Repository hmcts/adoption-web, pull requests merged in 2022-04, with the labels that each got.

#335 removed cpu and memory params from values.yaml
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  src/test/pact/ccd-data-store-api.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-335

#336 added secure flag to session cookie
  charts/adoption-web/values.preview.template.yaml
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
  src/main/server.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-336

#342 increased pod size for aat staging
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.aat.template.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-342

#343 made setLocalEndpoints private
  src/main/modules/properties-volume/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-343

#345 Applicant2 same address issue
  src/main/app/case/to-api-format.test.ts
  src/main/steps/applicant2/same-address/SameAddressPostController.test.ts
  src/main/steps/applicant2/same-address/SameAddressPostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-345

#347 Adop 691 a11y bugfix
  src/main/steps/children/placement-order-check-your-answers/content.test.ts
  src/main/steps/children/placement-order-check-your-answers/content.ts
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.test.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.test.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.ts
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-347

#348 zap issue fix
  audit.json
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-348

#340 content changes for welsh translation
  src/main/steps/accessibility-statement/content.test.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/applicant1/upload-your-documents/content.test.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant2/same-address/content.ts
  src/main/steps/birth-father/alive/content.ts
  src/main/steps/birth-father/alive/notSureInput/content.ts
  src/main/steps/birth-father/name-on-certificate/content.ts
  src/main/steps/birth-father/occupation/content.ts
  src/main/steps/children/find-family-court/content.test.ts
  src/main/steps/children/find-family-court/content.ts
  src/main/steps/children/full-name-after-adoption/content.test.ts
  src/main/steps/children/full-name-after-adoption/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/address-select.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/common/components/other-names.ts
  src/main/steps/contact-us/content.test.ts
  src/main/steps/contact-us/content.ts
  src/main/steps/eligibility/constants.ts
  src/main/steps/eligibility/domicile/content.test.ts
  src/main/steps/eligibility/lived-uk/content.test.ts
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/under-18/content.test.ts
  src/main/steps/eligibility/under-21/content.test.ts
  src/main/steps/error/content.ts
  src/main/steps/privacy-policy/content.test.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/task-list/content.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/terms-and-conditions/content.test.ts
  src/main/steps/terms-and-conditions/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-340

#351 modified providers
  src/test/pact/ccd-data-store-api.test.ts
  src/test/pact/dm-store.test.ts
  src/test/pact/fees-register-api.test.ts
  src/test/pact/idam-api.test.ts
  src/test/pact/payment-api.test.ts
  src/test/pact/rpe-service-auth-provider.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-351

#356 updated chart dependencies repository
  charts/adoption-web/Chart.yaml
  src/main/steps/review-pay-submit/check-your-answers/CheckYouAnswersPostController.test.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-356

#358 Zap change
  audit.json
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-358

#368 Nightly pipeline fix
  Jenkinsfile_nightly
  src/test/pact/ccd-data-store-api.test.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-368

#372 Adop 696 contact us
  src/main/app/form/Form.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us.njk
  src/main/steps/common/form/contactForHelp.njk
  src/main/steps/common/page.njk
  src/main/steps/eligibility/domicile/content.ts
  src/main/steps/eligibility/lived-uk/content.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/eligibility/under-18/content.ts
  src/main/steps/eligibility/under-21/content.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-372

#370 Adop 675 dynamic fee
  package.json
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/steps/eligibility/start/EligibilityStartGetController.test.ts
  src/main/steps/eligibility/start/EligibilityStartGetController.ts
  src/main/steps/eligibility/start/content.test.ts
  src/main/steps/eligibility/start/content.ts
  src/test/pact/fees-register-api.test.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-370

#397 changed secure cookie logic based on env variable
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-397
