Repository hmcts/adoption-web, pull requests merged in 2022-03, with the labels that each got.

#210 Adop 214 check your answers
  Jenkinsfile_nightly
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/app/controller/other-names/OtherNamesGetController.test.ts
  src/main/app/controller/other-names/OtherNamesGetController.ts
  src/main/app/controller/other-names/OtherNamesPostController.test.ts
  src/main/app/controller/other-names/OtherNamesPostController.ts
  src/main/assets/scss/main.scss
  src/main/modules/state-redirect/index.ts
  src/main/steps/birth-father/address/lookup/content.ts
  src/main/steps/birth-father/address/manual/content.ts
  src/main/steps/birth-father/address/select/content.ts
  src/main/steps/birth-father/birthFatherSequence.test.ts
  src/main/steps/birth-father/birthFatherSequence.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyGetController.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyPostController.ts
  src/main/steps/children/placement-order/PlacementOrderGetController.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/form.njk
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
  src/main/steps/sibling/placement-order/post.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/fixtures/caseData/childAdoptionAgencyDetails.js
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/dateChildMovedinDetails.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-210

#220 Footer links and their respective pages added.
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/accessibility-statement/get.ts
  src/main/steps/accessibility-statement/template.njk
  src/main/steps/cookies/content.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/cookies/get.ts
  src/main/steps/cookies/template.njk
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/privacy-policy/get.ts
  src/main/steps/privacy-policy/template.njk
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/terms-and-conditions/get.ts
  src/main/steps/terms-and-conditions/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-220

#217 Adop 414
  src/main/app/case/case.ts
  src/main/routes.ts
  src/main/steps/application-submitted/content.test.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/get.test.ts
  src/main/steps/application-submitted/get.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
  src/main/steps/task-list/utils.ts
  src/test/e2e/pages/reviewPayAndSubmit.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-217

#215 Content changes on Children sex at birth screen
  charts/adoption-web/Chart.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/form/Form.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/children/sex-at-birth/content.test.ts
  src/main/steps/children/sex-at-birth/content.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/address-select.ts
  src/main/steps/common/form/fields/select.njk
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-215

#224 ignored dynatrace monitor endpoint from csurf
  src/main/modules/csrf/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-224

#225 pcq attribute update
  charts/adoption-web/values.preview.template.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-225

#219 added pa11y tests in place of functional tests in pipeline
  package.json
  src/main/steps/applicant1/contact-details/content.test.ts
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/applicant1/occupation/content.test.ts
  src/main/steps/applicant1/occupation/content.ts
  src/main/steps/applicant2/contact-details/content.test.ts
  src/main/steps/applicant2/contact-details/content.ts
  src/main/steps/applicant2/full-name/content.test.ts
  src/main/steps/applicant2/full-name/content.ts
  src/main/steps/applicant2/occupation/content.test.ts
  src/main/steps/applicant2/occupation/content.ts
  src/main/steps/birth-father/alive/notSureInput/content.ts
  src/main/steps/birth-mother/occupation/content.test.ts
  src/main/steps/birth-mother/occupation/content.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/address-manual.ts
  src/main/steps/common/components/common/renderSubFields.test.ts
  src/main/steps/common/components/common/renderSubFields.ts
  src/main/steps/common/components/full-name.test.ts
  src/main/steps/common/components/full-name.ts
  src/main/steps/common/components/input.test.ts
  src/main/steps/common/components/input.ts
  src/main/steps/common/components/nationality.test.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/common/components/other-names.test.ts
  src/main/steps/common/components/other-names.ts
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/common/form/fields/input.njk
  src/main/steps/eligibility/start/template.njk
  src/main/steps/review-pay-submit/equality/get.ts
  src/main/steps/review-pay-submit/statement-of-truth/content.test.ts
  src/main/steps/review-pay-submit/statement-of-truth/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/a11y/a11y.ts.todo
  src/test/a11y/dummy-test.ts
  src/test/config.ts
  src/test/e2e/pages/taskList.page.js
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-219

#222 Check your answers content and navigation fix
  Jenkinsfile_CNP
  src/main/app/controller/PostController.ts
  src/main/app/nationality/NationalityPostController.ts
  src/main/steps/children/adoption-agency/AdoptionAgencyPostController.ts
  src/main/steps/children/placement-order/PlacementOrderGetController.ts
  src/main/steps/children/placement-order/PlacementOrderPostController.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/equality/get.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/childAdoptionCertificateDetails.page.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/e2e/pages/childBirthMothersDetails.page.js
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/e2e/pages/childSiblingDetails.page.js
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/chooseYourFamilyCourtDetails.page.js
  src/test/e2e/pages/dateChildMovedinDetails.page.js
  src/test/e2e/pages/otherApplicant.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/pages/uploadDocumentsDetails.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-222

#233 Pcq change
  charts/adoption-web/values.preview.template.yaml
  src/main/steps/children/find-family-court/util.test.ts
  src/main/steps/children/find-family-court/util.ts
  src/main/steps/review-pay-submit/equality/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-233

#260 updated pcq logs
  charts/adoption-web/values.preview.template.yaml
  src/main/steps/review-pay-submit/equality/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-260

#261 added downstream API smoke tests and report
  jest.smoke.config.js
  package.json
  src/test/smoke/smoke.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-261

#263 json-schema vulnerability fix
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-263

#274 Fortify scan hook added in the nightly.
  Jenkinsfile_nightly
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-274

#276 Fortify fixes added to make this work in pipeline.
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-276

#285 Pilot court emaiId updated in value.yaml for lower environments.
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.aat.template.yaml
  charts/adoption-web/values.demo.template.yaml
  charts/adoption-web/values.ithc.template.yaml
  charts/adoption-web/values.perftest.template.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.sandbox.template.yaml
  charts/adoption-web/values.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-285

#284 Integration tests config
  Jenkinsfile_CNP
  jest.integration.config.js
  package.json
  sonar-project.properties
  src/main/app/auth/service/get-service-auth-token.integration.test.ts
  src/main/app/auth/user/oidc.integration.test.ts
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/answers/formatDate.test.ts
  src/main/app/case/formatter/address.test.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.ts
  src/main/app/document/DocumentManagementClient.integration.test.ts
  src/main/app/fee/fee-lookup-api.integration.test.ts
  src/main/app/form/Form.test.ts
  src/main/app/payment/PaymentClient.integration.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/postcode/postcode-lookup-api.integration.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/review-pay-submit/equality/get.integration.test.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-284

#283 updated cookies page
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/cookie-banner/template.njk
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-283

#248 Adop 276 task list ordering
  src/main/app/auth/service/get-service-auth-token.integration.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/server.ts
  src/main/steps/task-list/content.test.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/test/e2e/pages/childAdoptionCertificateDetails.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-248

#264 ADOP-647 change
  src/main/steps/eligibility/start/content.test.ts
  src/main/steps/eligibility/start/content.ts
  src/main/steps/eligibility/start/template.njk
  src/main/steps/review-pay-submit/equality/get.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/test/e2e/pages/reviewPayAndSubmit.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-264

#291 stop ithc perftest branch sync
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-291

#303 Test commit to check the docker image version in ITHC and PerfTest.
  testfile.txt
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-303

#305 modified a11y yarn script
  Jenkinsfile_CNP
  package.json
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-305

#311 PCQ logging
  src/main/steps/review-pay-submit/equality/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-311

#312 changed pa11y output location
  src/test/a11y/a11y.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-312

#282 Fix Safari browser
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  saucelabs.conf.js
  src/test/config.ts
  src/test/e2e/crossbrowser/supportedBrowsers.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/childAdoptionCertificateDetails.page.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/e2e/pages/childBirthMothersDetails.page.js
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/e2e/pages/childSiblingDetails.page.js
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/chooseYourFamilyCourtDetails.page.js
  src/test/e2e/pages/dateChildMovedinDetails.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/pages/otherApplicant.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/pages/uploadDocumentsDetails.page.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/tests/smoke_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-282

#315 Adop 710 zap
  package.json
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-315

#316 Adop 710 zap
  audit.json
  security.sh
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-316

#320 ADOP-710 changes
  Jenkinsfile_nightly
  security.sh
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-320

#321 ADOP-710
  security.sh
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-321

#300 Added pact tests (consumer flavour)
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  broker-compose.yaml
  jest.pact.config.js
  package.json
  src/main/app/auth/service/get-service-auth-token.integration.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/case/CaseApi.ts
  src/test/pact/ccd-data-store-api.test.ts
  src/test/pact/dm-store.test.ts
  src/test/pact/fees-register-api.test.ts
  src/test/pact/idam-api.test.ts
  src/test/pact/payment-api.test.ts
  src/test/pact/postcode-lookup-api.test.ts
  src/test/pact/rpe-service-auth-provider.test.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-300

#323 Adop 710 zap
  Jenkinsfile_nightly
  security.sh
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-323

#324 Adop 710 zap
  security.sh
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-324

#272 Adop 415 error handling
  src/main/steps/common/common.content.ts
  src/main/steps/error/content.ts
  src/main/steps/error/error.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-272

#313 Adop 716 save language selection
  package.json
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/i18n/index.test.ts
  src/main/modules/i18n/index.ts
  src/main/modules/oidc/index.ts
  src/main/server.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-313

#322 Upload document file format updated. | Welsh language handling in payment client. | PostController.test.ts test file updated.
  src/main/app/controller/PostController.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/steps/applicant1/upload-your-documents/content.test.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-322

#330 added survey link
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-330

#331 Fixed accessibility issue on privacy policy page.
  src/main/steps/privacy-policy/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-331

#332 fixed sonar error
  src/main/steps/task-list/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-332
