Repository hmcts/adoption-web, pull requests merged in 2022-08, with the labels that each got.

#655 dynamic ref api url based on env
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-655

#662 LOCATION_API_URL update
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-662

#674 preview issue
  charts/adoption-web/values.preview.template.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-674

#676 task-list changes
  src/main/steps/application/task-list/content.test.ts
  src/main/steps/application/task-list/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-676

#684 Local config changes for tls
  config/default.yaml
  package.json
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-684

#682 updated check-your answer page
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-682

#689 Adop 1086 & 1130
  charts/adoption-web/values.preview.template.yaml
  codecept.conf.js
  config/default.yaml
  draft-store.yml
  saucelabs.conf.js
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/kba/index.ts
  src/main/steps/application/task-list/utils.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/statement-of-truth/content.test.ts
  src/main/steps/la-portal/statement-of-truth/content.ts
  src/main/steps/la-portal/statement-of-truth/form.njk
  src/main/steps/la-portal/statement-of-truth/template.njk
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/la-portal/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/laCheckYourAnswers.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/pages/uploadDocumentsDetails.page.js
  src/test/e2e/tests/saveAsDraft_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-689

#693 Adop 1086
  codecept.conf.js
  config/default.yaml
  draft-store.yml
  saucelabs.conf.js
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/kba/index.ts
  src/main/steps/application/task-list/utils.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/statement-of-truth/content.test.ts
  src/main/steps/la-portal/statement-of-truth/content.ts
  src/main/steps/la-portal/statement-of-truth/form.njk
  src/main/steps/la-portal/statement-of-truth/template.njk
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/la-portal/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/laCheckYourAnswers.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/pages/uploadDocumentsDetails.page.js
  src/test/e2e/tests/saveAsDraft_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-693

#705 Logger update
  src/main/modules/draft-store/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-705

#709 OIDC role check disabled
  src/main/modules/oidc/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-709

#712 Add backstage configuration file
  catalog-info.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-712

#703 Enabled Pally tests for LA_PORTAL
  src/main/steps/la-portal/confirmation/template.njk
  src/main/steps/la-portal/task-list/template.njk
  src/test/a11y/a11y.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-703
