Repository hmcts/adoption-web, pull requests merged in 2022-06, with the labels that each got.

#515 Save-as-draft change
  codecept.conf.js
  saucelabs.conf.js
  src/main/app/controller/PostController.ts
  src/main/app/nationality/NationalityPostController.ts
  src/main/steps/application/applicationSequence.test.ts
  src/main/steps/application/applicationSequence.ts
  src/main/steps/application/save-as-draft/content.test.ts
  src/main/steps/application/save-as-draft/content.ts
  src/main/steps/application/save-as-draft/post.test.ts
  src/main/steps/application/save-as-draft/post.ts
  src/main/steps/application/save-as-draft/template.njk
  src/main/steps/urls.ts
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/e2e/pages/saveAsDraft.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/saveAsDraft_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-515

#528 updated child details pages
  codecept.conf.js
  saucelabs.conf.js
  src/main/steps/application/task-list/content.test.ts
  src/main/steps/application/task-list/content.ts
  src/main/steps/application/task-list/utils.test.ts
  src/main/steps/application/task-list/utils.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/full-name-after-adoption/content.test.ts
  src/main/steps/children/full-name-after-adoption/content.ts
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/childsDetails.page.js
  src/test/e2e/tests/e2enegative_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-528

#519 added google analytics
  src/main/assets/js/cookie.ts
  src/main/modules/helmet/index.ts
  src/main/modules/session/index.test.ts
  src/main/modules/session/index.ts
  src/main/server.ts
  src/main/steps/common/page.njk
  src/main/steps/cookie-banner/template.njk
  src/main/steps/cookies/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-519

#555 Updated yarn audit.
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-555

#557 Cookies fix.
  src/main/assets/js/cookie.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-557

#558 ITHC added in the branchesToSync array as requested by ITHC arch for …
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-558

#559 Elastic search API implementation to fetch the case from data store.
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/CaseApi.ts
  src/test/steps/common.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-559

#556 Adop 985 welsh translation
  src/main/steps/applicant1/upload-your-documents/content.test.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/application/save-as-draft/content.test.ts
  src/main/steps/application/save-as-draft/content.ts
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/task-list/content.test.ts
  src/main/steps/application/task-list/content.ts
  src/main/steps/children/full-name-after-adoption/content.test.ts
  src/main/steps/children/full-name-after-adoption/content.ts
  src/main/steps/eligibility/start/content.test.ts
  src/main/steps/eligibility/start/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-556

#529 ADOP-954 changes
  config/default.yaml
  src/main/app/court/court-venues-api.integration.test.ts
  src/main/app/court/court-venues-api.ts
  src/main/app/court/location.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-529

#564 Adop 983
  Jenkinsfile_CNP
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/task-list/content.test.ts
  src/main/steps/la-portal/task-list/content.ts
  src/main/steps/other-parent/address-known/content.test.ts
  src/main/steps/other-parent/address-known/content.ts
  src/main/steps/other-parent/address/lookup/form.njk
  src/main/steps/other-parent/address/manual/form.njk
  src/main/steps/other-parent/address/select/form.njk
  src/main/steps/other-parent/exists/content.test.ts
  src/main/steps/other-parent/exists/content.ts
  src/main/steps/other-parent/full-name/content.test.ts
  src/main/steps/other-parent/full-name/content.ts
  src/main/steps/other-parent/last-address-confirmed/content.test.ts
  src/main/steps/other-parent/last-address-confirmed/content.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/pact/ccd-data-store-api.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-564

#582 ADOP-1031 Test changes
  src/test/e2e/pages/dateChildMovedinDetails.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-582

#578 Footer links with la-portal context path when used from LA portal.
  src/main/steps/application/privacy-policy/content.test.ts
  src/main/steps/application/privacy-policy/content.ts
  src/main/steps/application/privacy-policy/template.njk
  src/main/steps/application/terms-and-conditions/content.test.ts
  src/main/steps/application/terms-and-conditions/content.ts
  src/main/steps/application/terms-and-conditions/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/cookie-banner.njk
  src/main/steps/common/page.njk
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-578

#588 ADOP 1017
  src/main/steps/la-portal/kba-case-ref/content.test.ts
  src/main/steps/la-portal/kba-case-ref/content.ts
  src/test/e2e/pages/LandingPage.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-588

#584 FPET-38 Updated error message for Child Move in date
  Jenkinsfile_nightly
  src/main/steps/applicant1/date-child-moved-in/content.test.ts
  src/main/steps/applicant1/date-child-moved-in/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-584
