Repository hmcts/adoption-web, pull requests merged in 2022-12, with the labels that each got.

#898 Accessibility Testing Issues (Re-test results) - CUI & LA Portal
  src/main/steps/applicant1/contact-details/content.test.ts
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/children/find-family-court/FindFamilyCourtPostController.ts
  src/main/steps/children/find-family-court/content.test.ts
  src/main/steps/children/find-family-court/content.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.ts
  src/main/steps/children/find-placement-order-court/content.test.ts
  src/main/steps/children/find-placement-order-court/content.ts
  src/main/steps/children/placement-order-court/content.test.ts
  src/main/steps/children/placement-order-court/content.ts
  src/main/steps/common/form/fields/select-dropdown.njk
  src/main/steps/review-pay-submit/statement-of-truth/content.test.ts
  src/main/steps/review-pay-submit/statement-of-truth/content.ts
  src/test/e2e/pages/chooseYourFamilyCourtDetails.page.js
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-898

#906 ADOP-1886: Terraform version upgrade
  infrastructure/.terraform-version
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-906

#914 Upgrade terraform to version 1.3.6
  infrastructure/.terraform-version
  infrastructure/versions.tf
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-914
