Repository hmcts/adoption-web, pull requests merged in 2022-07, with the labels that each got.

#597 removed cross browser array
  Jenkinsfile_nightly
  saucelabs.conf.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-597

#601 Feedback link for la-portal
  src/main/steps/common/page.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-601

#604 unused browsers are commented
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-604

#612 Adding fixes for security scan
  audit.json
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-612

#607 Task list modifications
  src/main/steps/la-portal/task-list/content.ts
  src/main/steps/la-portal/task-list/template.njk
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/la-portal/task-list/utils.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-607

#614 Adop 980
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/steps/application/task-list/utils.test.ts
  src/main/steps/la-portal/task-list/content.test.ts
  src/main/steps/la-portal/task-list/content.ts
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/sibling/exists/content.test.ts
  src/main/steps/sibling/exists/content.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.test.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.ts
  src/main/steps/sibling/placement-order-type/content.test.ts
  src/main/steps/sibling/placement-order-type/content.ts
  src/main/steps/sibling/placement-order/get.test.ts
  src/main/steps/sibling/placement-order/get.ts
  src/main/steps/sibling/placement-order/post.ts
  src/main/steps/sibling/relation/SiblingGetController.test.ts
  src/main/steps/sibling/relation/SiblingGetController.ts
  src/main/steps/sibling/relation/SiblingPostController.ts
  src/main/steps/sibling/relation/content.test.ts
  src/main/steps/sibling/relation/content.ts
  src/main/steps/sibling/remove-placement-order/content.test.ts
  src/main/steps/sibling/remove-placement-order/content.ts
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
  src/main/steps/sibling/summary/content.test.ts
  src/main/steps/sibling/summary/content.ts
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
  src/test/a11y/a11y.ts
  src/test/e2e/pages/childSiblingDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-614

#617 Adop 998 confirmation
  src/main/steps/la-portal/confirmation/content.test.ts
  src/main/steps/la-portal/confirmation/content.ts
  src/main/steps/la-portal/confirmation/template.njk
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/task-list/content.ts
  src/main/steps/la-portal/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-617

#377 ADOP-817 changes for CDAM integration
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/document/DocumentManagementClient.integration.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/properties-volume/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-377

#620 ADOP - 1094 - Update Adoption Agency Social Worker Email Hint
  src/main/steps/children/applicant-social-worker/content.test.ts
  src/main/steps/children/applicant-social-worker/content.ts
  src/main/steps/children/social-worker/content.test.ts
  src/main/steps/children/social-worker/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-620

#619 ADOP - 1115 - La Portal Death Certificate
  src/main/steps/birth-father/alive/content.test.ts
  src/main/steps/birth-father/alive/content.ts
  src/main/steps/birth-father/alive/notSureInput/content.ts
  src/main/steps/birth-father/alive/template.njk
  src/main/steps/birth-mother/still-alive/content.ts
  src/main/steps/birth-mother/still-alive/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-619

#629 Update Chart.yaml
  charts/adoption-web/Chart.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-629

#631 resolved conflict
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/auth/user/oidc.integration.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/court/court-venues-api.integration.test.ts
  src/main/app/document/DocumentManagementClient.integration.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-631

#633 Upgraded nodeJs in chart
  charts/adoption-web/Chart.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-633

#622 ADOP 1072 La Portal Nationality
  src/main/steps/birth-father/nationality/content.test.ts
  src/main/steps/birth-father/nationality/content.ts
  src/main/steps/birth-mother/nationality/content.test.ts
  src/main/steps/birth-mother/nationality/content.ts
  src/main/steps/children/nationality/content.test.ts
  src/main/steps/children/nationality/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-622

#642 Added to ignore list in audit.json
  audit.json
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-642

#613 ADOP - 1081 - Security page error messages
  src/main/app/case/case.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/kba/index.ts
  src/main/steps/la-portal/kba-case-ref/content.test.ts
  src/main/steps/la-portal/kba-case-ref/content.ts
  src/main/steps/la-portal/kba-case-ref/get.test.ts
  src/main/steps/la-portal/kba-case-ref/get.ts
  src/main/steps/la-portal/kba-case-ref/post.test.ts
  src/main/steps/la-portal/kba-case-ref/post.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/negative-scenario/content.test.ts
  src/main/steps/la-portal/negative-scenario/content.ts
  src/main/steps/la-portal/negative-scenario/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/e2e/pages/LandingPage.js
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-613

#635 Adop 993 review your answers part1
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/form.njk
  src/main/steps/la-portal/check-your-answers/template.njk
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/task-list/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-635

#646 Add contact us section la portal
  src/main/steps/common/form/contactForHelp.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-646

#641 ADOP 1073 Orders summary page
  src/main/steps/children/placement-order-number/content.test.ts
  src/main/steps/children/placement-order-number/content.ts
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/content.ts
  src/main/steps/children/placement-order-type/content.test.ts
  src/main/steps/children/placement-order-type/content.ts
  src/main/steps/sibling/summary/content.test.ts
  src/main/steps/sibling/summary/content.ts
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-641

#648 Adop 1153
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/court/court-venues-api.ts
  src/main/modules/draft-store/draft-store-service.test.ts
  src/main/modules/draft-store/draft-store-service.ts
  src/main/modules/draft-store/index.ts
  src/main/modules/kba/index.ts
  src/main/modules/session/index.test.ts
  src/main/server.ts
  src/main/steps/children/find-family-court/content.ts
  src/main/steps/children/placement-order/PlacementOrderPostController.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/la-portal/task-list/template.njk
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-648

#640 ADOP-1129-LA Portal - Review your answers functionality - Part 2
  src/main/app/controller/PostController.ts
  src/main/modules/kba/index.ts
  src/main/steps/birth-father/alive/template.njk
  src/main/steps/birth-mother/still-alive/template.njk
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/start-page/content.test.ts
  src/main/steps/la-portal/start-page/content.ts
  src/main/steps/la-portal/start-page/template.njk
  src/main/steps/la-portal/task-list/content.ts
  src/main/steps/sibling/placement-order/post.ts
  src/main/steps/sibling/relation/SiblingPostController.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/taskList.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-640
