Repository hmcts/adoption-web, pull requests merged in 2022-01, with the labels that each got.

#72 Adop 299 placement order subtask
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  codecept.conf.js
  jest.config.js
  package.json
  src/main/app/case/answers/formatDate.test.ts
  src/main/app/case/answers/formatDate.ts
  src/main/app/case/case.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/placement-order-check-your-answers/content.test.ts
  src/main/steps/children/placement-order-check-your-answers/content.ts
  src/main/steps/children/placement-order-check-your-answers/form.njk
  src/main/steps/children/placement-order-check-your-answers/get.test.ts
  src/main/steps/children/placement-order-check-your-answers/get.ts
  src/main/steps/children/placement-order-check-your-answers/template.njk
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/content.ts
  src/main/steps/children/placement-order-summary/get.test.ts
  src/main/steps/children/placement-order-summary/get.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.test.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.ts
  src/main/steps/children/placement-order-type/content.test.ts
  src/main/steps/children/placement-order-type/content.ts
  src/main/steps/children/placement-order-type/get.test.ts
  src/main/steps/children/placement-order-type/get.ts
  src/main/steps/children/placement-order-type/post.test.ts
  src/main/steps/children/placement-order-type/post.ts
  src/main/steps/children/placement-order/get.test.ts
  src/main/steps/children/placement-order/get.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/config.js
  src/test/e2e/pages/childAdoptionCertificateDetails.page.js
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-72

#75 Master Functional Fix
  Jenkinsfile_CNP
  package.json
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/eligibility_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-75

#76 Master fix new
  Jenkinsfile_nightly
  src/test/e2e/config.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-76

#77 URL fix
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-77

#78 typo fix
  src/main/steps/applicant1/address/lookup/content.test.ts
  src/main/steps/applicant1/address/lookup/content.ts
  src/main/steps/applicant2/address/lookup/content.test.ts
  src/main/steps/applicant2/address/lookup/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-78

#81 Cross browser config in nightly
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  package.json
  saucelabs.conf.js
  src/test/e2e/crossbrowser/supportedBrowsers.js
  src/test/e2e/helpers/SauceLabsReportingHelper.js
  src/test/e2e/tests/eligibility_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-81

#83 added common component for international address
  src/main/steps/common/components/address-international.test.ts
  src/main/steps/common/components/address-international.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/address-manual.ts
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-83

#82 Changes in Config file
  Jenkinsfile_CNP
  src/test/e2e/config.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-82

#85 Nationality code optimisation
  src/main/app/form/Form.ts
  src/main/app/form/validation.ts
  src/main/app/nationality/NationalityGetController.test.ts
  src/main/app/nationality/NationalityGetController.ts
  src/main/app/nationality/NationalityPostController.test.ts
  src/main/app/nationality/NationalityPostController.ts
  src/main/steps/applicant1/nationality/content.test.ts
  src/main/steps/applicant1/nationality/content.ts
  src/main/steps/applicant1/nationality/get.test.ts
  src/main/steps/applicant1/nationality/get.ts
  src/main/steps/applicant1/nationality/post.test.ts
  src/main/steps/applicant1/nationality/post.ts
  src/main/steps/applicant2/nationality/get.test.ts
  src/main/steps/applicant2/nationality/get.ts
  src/main/steps/applicant2/nationality/post.test.ts
  src/main/steps/applicant2/nationality/post.ts
  src/main/steps/children/nationality/content.test.ts
  src/main/steps/children/nationality/content.ts
  src/main/steps/children/nationality/get.test.ts
  src/main/steps/children/nationality/get.ts
  src/main/steps/children/nationality/post.test.ts
  src/main/steps/children/nationality/post.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/nationality.test.ts
  src/main/steps/common/components/nationality.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-85

#73 Adop 208 birth mother details
  Jenkinsfile_nightly
  codecept.conf.js
  saucelabs.conf.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/full-name/content.test.ts
  src/main/steps/applicant1/full-name/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/birth-mother/address-known/content.test.ts
  src/main/steps/birth-mother/address-known/content.ts
  src/main/steps/birth-mother/address/international/content.test.ts
  src/main/steps/birth-mother/address/international/content.ts
  src/main/steps/birth-mother/address/international/template.njk
  src/main/steps/birth-mother/address/lookup/content.test.ts
  src/main/steps/birth-mother/address/lookup/content.ts
  src/main/steps/birth-mother/address/lookup/form.njk
  src/main/steps/birth-mother/address/lookup/post.test.ts
  src/main/steps/birth-mother/address/lookup/post.ts
  src/main/steps/birth-mother/address/lookup/template.njk
  src/main/steps/birth-mother/address/manual/content.test.ts
  src/main/steps/birth-mother/address/manual/content.ts
  src/main/steps/birth-mother/address/manual/form.njk
  src/main/steps/birth-mother/address/manual/template.njk
  src/main/steps/birth-mother/address/select/content.test.ts
  src/main/steps/birth-mother/address/select/content.ts
  src/main/steps/birth-mother/address/select/form.njk
  src/main/steps/birth-mother/address/select/post.test.ts
  src/main/steps/birth-mother/address/select/post.ts
  src/main/steps/birth-mother/address/select/template.njk
  src/main/steps/birth-mother/birthMotherSequence.test.ts
  src/main/steps/birth-mother/birthMotherSequence.ts
  src/main/steps/birth-mother/full-name/content.test.ts
  src/main/steps/birth-mother/full-name/content.ts
  src/main/steps/birth-mother/nationality/content.test.ts
  src/main/steps/birth-mother/nationality/content.ts
  src/main/steps/birth-mother/nationality/get.test.ts
  src/main/steps/birth-mother/nationality/get.ts
  src/main/steps/birth-mother/nationality/post.test.ts
  src/main/steps/birth-mother/nationality/post.ts
  src/main/steps/birth-mother/occupation/content.test.ts
  src/main/steps/birth-mother/occupation/content.ts
  src/main/steps/birth-mother/still-alive/content.test.ts
  src/main/steps/birth-mother/still-alive/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/components/address-international.test.ts
  src/main/steps/common/components/address-international.ts
  src/main/steps/common/components/full-name.test.ts
  src/main/steps/common/components/full-name.ts
  src/main/steps/common/components/nationality.test.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/index.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childBirthMothersDetails.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-73

#84 ADOP 215 Other parent details
  codecept.conf.js
  saucelabs.conf.js
  src/main/app/case/case.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/index.ts
  src/main/steps/other-parent/address-known/content.test.ts
  src/main/steps/other-parent/address-known/content.ts
  src/main/steps/other-parent/address/international/content.test.ts
  src/main/steps/other-parent/address/international/content.ts
  src/main/steps/other-parent/address/international/template.njk
  src/main/steps/other-parent/address/lookup/content.test.ts
  src/main/steps/other-parent/address/lookup/content.ts
  src/main/steps/other-parent/address/lookup/form.njk
  src/main/steps/other-parent/address/lookup/post.test.ts
  src/main/steps/other-parent/address/lookup/post.ts
  src/main/steps/other-parent/address/lookup/template.njk
  src/main/steps/other-parent/address/manual/content.test.ts
  src/main/steps/other-parent/address/manual/content.ts
  src/main/steps/other-parent/address/manual/form.njk
  src/main/steps/other-parent/address/manual/template.njk
  src/main/steps/other-parent/address/select/content.test.ts
  src/main/steps/other-parent/address/select/content.ts
  src/main/steps/other-parent/address/select/form.njk
  src/main/steps/other-parent/address/select/post.test.ts
  src/main/steps/other-parent/address/select/post.ts
  src/main/steps/other-parent/address/select/template.njk
  src/main/steps/other-parent/constants.ts
  src/main/steps/other-parent/exists/content.test.ts
  src/main/steps/other-parent/exists/content.ts
  src/main/steps/other-parent/full-name/content.test.ts
  src/main/steps/other-parent/full-name/content.ts
  src/main/steps/other-parent/otherParentSequence.test.ts
  src/main/steps/other-parent/otherParentSequence.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-84

#87 ADOP-295 | Fee and Pay callback service implemented
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/docker.yaml
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/payment/PaymentModel.test.ts
  src/main/app/payment/PaymentModel.ts
  src/main/app/payment/__mocks__/PaymentClient.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/template.njk
  src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
  src/main/steps/review-pay-submit/payment/payment-callback/template.njk
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts
  src/main/steps/task-list/content.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-87

#94 Common component improvements
  config/development.yaml
  package.json
  src/main/steps/birth-father/address-known/content.ts
  src/main/steps/birth-father/alive/content.ts
  src/main/steps/birth-father/alive/notSureInput/content.ts
  src/main/steps/birth-father/name-on-certificate/content.ts
  src/main/steps/birth-father/occupation/content.ts
  src/main/steps/common/components/common/component.test.ts
  src/main/steps/common/components/common/component.ts
  src/main/steps/common/components/common/default-buttons.ts
  src/main/steps/common/components/common/renderSubFields.test.ts
  src/main/steps/common/components/common/renderSubFields.ts
  src/main/steps/common/components/common/types.ts
  src/main/steps/common/components/input.test.ts
  src/main/steps/common/components/input.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/common/components/radios.test.ts
  src/main/steps/common/components/radios.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-94

#95 improved sequence file logic
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/steps/applicant1/applicant1Sequence.test.ts
  src/main/steps/applicant1/applicant1Sequence.ts
  src/main/steps/applicant2/applicant2Sequence.ts
  src/main/steps/birth-father/birthFatherSequence.ts
  src/main/steps/birth-mother/birthMotherSequence.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/constants.ts
  src/main/steps/eligibility/eligibilitySequence.test.ts
  src/main/steps/eligibility/eligibilitySequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts
  yarn-audit-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-95

#96 ADOP 210 ccd mapping
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-96

#97 Case file cleanup
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/modules/oidc/index.ts
  src/main/steps/applicant1/your-names-on-certificate/content.ts
  src/main/steps/applicant1/your-names-on-certificate/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/timed-out/get.test.ts
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/steps/check-your-answers.ts
  src/test/steps/common.ts
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-97

#123 added logic to skip required validation on saveAsDraft
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/validation.ts
  src/main/app/nationality/NationalityPostController.ts
  src/main/steps/children/placement-order/post.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-123

#98 ADOP 417 Other names split into firstnames and lastnames
  .eslintignore
  codecept.conf.js
  config/default.yaml
  package.json
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/other-names/OtherNamesGetController.test.ts
  src/main/app/controller/other-names/OtherNamesGetController.ts
  src/main/app/controller/other-names/OtherNamesPostController.test.ts
  src/main/app/controller/other-names/OtherNamesPostController.ts
  src/main/app/form/validation.ts
  src/main/steps/applicant1/other-names/content.test.ts
  src/main/steps/applicant1/other-names/content.ts
  src/main/steps/applicant1/other-names/get.test.ts
  src/main/steps/applicant1/other-names/get.ts
  src/main/steps/applicant1/other-names/post.test.ts
  src/main/steps/applicant1/other-names/post.ts
  src/main/steps/applicant2/other-names/content.test.ts
  src/main/steps/applicant2/other-names/content.ts
  src/main/steps/applicant2/other-names/get.test.ts
  src/main/steps/applicant2/other-names/get.ts
  src/main/steps/applicant2/other-names/post.test.ts
  src/main/steps/applicant2/other-names/post.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/common/components/other-names.test.ts
  src/main/steps/common/components/other-names.ts
  src/main/steps/common/functions/mapSummaryListContent.ts
  src/main/steps/task-list/utils.test.ts
  src/test/config.js
  src/test/config.ts
  src/test/e2e/actors/base.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/e2e/pages/childBirthMothersDetails.page.js
  src/test/e2e/pages/childrenBirthCertificate.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/tests/childDetails_test.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/otherApplicantDetails_test.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/taskList_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-98

#137 Other names error handling
  src/main/app/case/case.ts
  src/main/app/controller/other-names/OtherNamesGetController.ts
  src/main/app/controller/other-names/OtherNamesPostController.test.ts
  src/main/app/controller/other-names/OtherNamesPostController.ts
  src/main/app/form/Form.ts
  src/main/assets/js/index.ts
  src/main/assets/js/other-names/submit.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/common/components/other-names.ts
  src/main/steps/common/form/fields/details.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-137

#139 show ccd message change
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/controller/PostController.ts
  src/main/app/controller/other-names/OtherNamesGetController.ts
  src/main/app/controller/other-names/OtherNamesPostController.ts
  src/main/app/nationality/NationalityGetController.ts
  src/main/app/nationality/NationalityPostController.ts
  src/main/steps/children/placement-order/get.ts
  src/main/steps/children/placement-order/post.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-139

#121 Adop 297 sibling
  codecept.conf.js
  saucelabs.conf.js
  src/main/app/case/case.ts
  src/main/steps/constants.ts
  src/main/steps/index.ts
  src/main/steps/sibling/constants.ts
  src/main/steps/sibling/court-order-exists/content.test.ts
  src/main/steps/sibling/court-order-exists/content.ts
  src/main/steps/sibling/exists/content.test.ts
  src/main/steps/sibling/exists/content.ts
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/urls.ts
  src/test/e2e/pages/childSiblingDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-121

#140 Nightly cross browser fix
  .eslintignore
  codecept.conf.js
  saucelabs.conf.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-140

#122 ADOP 210 change
  Jenkinsfile_CNP
  codecept.conf.js
  saucelabs.conf.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/children/adoption-agency/content.test.ts
  src/main/steps/children/adoption-agency/content.ts
  src/main/steps/children/adoption-agency/get.test.ts
  src/main/steps/children/adoption-agency/get.ts
  src/main/steps/children/adoption-agency/post.test.ts
  src/main/steps/children/adoption-agency/post.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/other-adoption-agency/content.test.ts
  src/main/steps/children/other-adoption-agency/content.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/config.ts
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/otherApplicantDetails_test.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/taskList_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-122

#146 Adop 339 dynamic task list
  README.md
  package.json
  src/main/app/controller/PostController.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/home/get.ts
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/applicantDetails_test.js
  yarn-audit-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-146

#158 unit test coverage report archival
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-158

#152 ADOP-211 change
  src/main/steps/children/adoption-agency/content.test.ts
  src/main/steps/children/childrenSequence.test.ts
  src/main/steps/children/childrenSequence.ts
  src/main/steps/children/social-worker/content.test.ts
  src/main/steps/children/social-worker/content.ts
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/pages/otherApplicant.page.js
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-152

#171 Payment api integration
  config/default.yaml
  src/main/app/case/definition.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/fee/fee-lookup-api.test.ts
  src/main/app/fee/fee-lookup-api.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/steps/applicant1/applicant1Sequence.test.ts
  src/main/steps/applicant1/applicant1Sequence.ts
  src/main/steps/applicant1/fee-lookup/content.test.ts
  src/main/steps/applicant1/fee-lookup/content.ts
  src/main/steps/applicant1/fee-lookup/get.ts
  src/main/steps/common/common.content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/content.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/get.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.test.ts
  src/main/steps/review-pay-submit/payment/pay-your-fee/post.ts
  src/main/steps/task-list/template.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockFeeLookupResponses.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-171

#169 Adop 11
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/children/social-worker/content.test.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts
  src/main/steps/review-pay-submit/statement-of-truth/content.test.ts
  src/main/steps/review-pay-submit/statement-of-truth/content.ts
  src/main/steps/review-pay-submit/statement-of-truth/form.njk
  src/main/steps/review-pay-submit/statement-of-truth/template.njk
  src/main/steps/task-list/content.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-169

#159 Adop 445 sibling names
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/sibling/name/content.test.ts
  src/main/steps/sibling/name/content.ts
  src/main/steps/sibling/name/get.test.ts
  src/main/steps/sibling/name/get.ts
  src/main/steps/sibling/name/post.test.ts
  src/main/steps/sibling/name/post.ts
  src/main/steps/sibling/placement-order-number/content.test.ts
  src/main/steps/sibling/placement-order-number/content.ts
  src/main/steps/sibling/placement-order-number/get.test.ts
  src/main/steps/sibling/placement-order-number/get.ts
  src/main/steps/sibling/placement-order-number/post.test.ts
  src/main/steps/sibling/placement-order-number/post.ts
  src/main/steps/sibling/placement-order-type/content.test.ts
  src/main/steps/sibling/placement-order-type/content.ts
  src/main/steps/sibling/placement-order-type/get.test.ts
  src/main/steps/sibling/placement-order-type/get.ts
  src/main/steps/sibling/placement-order-type/post.test.ts
  src/main/steps/sibling/placement-order-type/post.ts
  src/main/steps/sibling/placement-order/get.test.ts
  src/main/steps/sibling/placement-order/get.ts
  src/main/steps/sibling/placement-order/post.test.ts
  src/main/steps/sibling/placement-order/post.ts
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
  src/main/steps/sibling/summary/content.test.ts
  src/main/steps/sibling/summary/content.ts
  src/main/steps/sibling/summary/form.njk
  src/main/steps/sibling/summary/get.test.ts
  src/main/steps/sibling/summary/get.ts
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
  src/main/steps/sibling/summary/template.njk
  src/main/steps/task-list/content.ts
  src/main/steps/task-list/template.njk
  src/main/steps/task-list/utils.test.ts
  src/main/steps/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childSiblingDetails.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/childDetails_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-159

#160 Sonar config correction
  package-lock.json
  sonar-project.properties
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-160

#174 fixed sonar issue
  src/main/steps/sibling/siblingSequence.test.ts
  src/main/steps/sibling/siblingSequence.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-174

#176 added few files to sonar exclusion temporarily
  sonar-project.properties
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-176

#178 increased duplication param values in sonar config
  sonar-project.properties
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-178

#175 Nightly fix
  Jenkinsfile_nightly
  saucelabs.conf.js
  src/test/e2e/pages/login.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-175

#180 E2E for Review and Pay
  codecept.conf.js
  saucelabs.conf.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/pages/primaryApplicant.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/pages/taskList.page.js
  src/test/e2e/tests/applicantDetails_test.js
  src/test/e2e/tests/childDetails_test.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/otherApplicantDetails_test.js
  src/test/e2e/tests/primaryApplicantDetails_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/e2e/tests/taskList_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-180
