Repository hmcts/adoption-web, pull requests merged in 2023-04, with the labels that each got.

#1102 Release 1.1 build issue
  .nvmrc
  Jenkinsfile_CNP
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
  src/test/e2e/config.js
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1102

#1103 FPET-492 fixed vulnarabilities issues
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1103

#1105 Updated the text content on eligibility screen
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1105

#1106 FPET-492 master build
  Jenkinsfile_CNP
  src/test/e2e/config.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1106

#1115 FPET-498/499- ITHC Issues-updated dependencies
  charts/adoption-web/Chart.yaml
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1115

#1111 Upgrade Yarn to Yarn Berry (v2)
  .dockerignore
  .gitignore
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  src/main/steps/common/webpack/css.njk
  src/main/steps/common/webpack/js.njk
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1111

#1122 Delete security.sh
  security.sh
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1122

#1126 Master rebase
  .dockerignore
  .gitignore
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  Dockerfile
  Jenkinsfile_CNP
  charts/adoption-web/values.yaml
  package.json
  security.sh
  src/main/steps/common/webpack/css.njk
  src/main/steps/common/webpack/js.njk
  src/test/e2e/config.js
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1126

#1121 CDAM changes
  charts/adoption-web/values.preview.template.yaml
  config/default.yaml
  package.json
  src/main/app/document/DocumentManagementController.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1121

#1131 FPET-522 suppressed vulnerabilities
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1131

#1134 Feature fpet 525 master sync
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1134

#1135 473 testfailure
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1135

#1109 FPET 473- removed eligibility start now page post IDAM login
  src/main/steps/applicant1/applicant1Sequence.test.ts
  src/main/steps/applicant1/applicant1Sequence.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/eligibility_test.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1109

#1140 FPET-473 Staging URL fix
  Jenkinsfile_CNP
  src/test/e2e/config.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1140

#1141 Master rebase
  Jenkinsfile_CNP
  src/test/e2e/config.js
  src/test/e2e/tests/eligibility_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1141
