Repository hmcts/adoption-web, pull requests merged in 2023-10, with the labels that each got.

#1386 SNI-4802-fetch successful payment details
  package.json
  src/main/app/payment/PaymentModel.ts
Labels: ns:adoption, prd:adoption, no-changes, enable_keep_helm, rel:adoption-web-pr-1386

#1401 FPET-718-Adoption Tranche 2 Court email address Release
  src/main/steps/children/find-family-court/util.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1401

#1402 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:adoption, prd:adoption, destroy, rel:adoption-web-pr-1402

#1412 sync demo, ithc and perftest with master
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1412

#1417 FPET-745-added LA email to allowed domain list
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1417

#1418 SNI-4802- Payment issue fix
  charts/adoption-web/values.preview.template.yaml
  src/main/steps/application/task-list/utils.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1418

#1423 FPET-749-added LA email domain to allowed list
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1423

#1433 FPET-719-Adoption Tranche 3 Court email address Release
  src/main/steps/children/find-family-court/util.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1433

#1439 FPET-764-added LA email domain to allowed list
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1439

#1422 FPET-572-accessibility page changes
  src/main/steps/application/accessibility-statement/content.test.ts
  src/main/steps/application/accessibility-statement/content.ts
  src/main/steps/application/accessibility-statement/template.njk
Labels: ns:adoption, prd:adoption, enable_keep_helm, add-or-update, rel:adoption-web-pr-1422

#1440 Sonar fixes prod
  src/main/steps/application/task-list/utils.test.ts
  src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1440

#1441 FPET-764-corrected LA domain from allowed list
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1441
