Repository hmcts/adoption-web, pull requests merged in 2023-07, with the labels that each got.

#1230 Feature post release 1.1 to master
  sonar-project.properties
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/assets/scss/task-list.scss
  src/main/steps/application/task-list/template.njk
  src/main/steps/children/full-name/content.test.ts
  src/main/steps/children/full-name/content.ts
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/la-portal/task-list/content.ts
  src/main/steps/la-portal/task-list/template.njk
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1230

#1241 SNI-4275
  src/main/app/form/validation.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1241

#1245 SNI-4308-whitelisted another LA email
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1245

#1237 FPET-613
  src/main/assets/js/applying-with-button-disable.ts
  src/main/assets/js/index.ts
  src/main/steps/application/applying-with/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1237

#1251 SNI-4302- Payment Back Button issue fix
  src/main/steps/review-pay-submit/payment/payment-callback/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1251
