Repository hmcts/adoption-web, pull requests merged in 2023-05, with the labels that each got.

#1145 Feature fpet 529 junit
  src/main/app/controller/PostController.test.ts
  src/main/steps/review-pay-submit/check-your-answers/CheckYouAnswersPostController.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1145

#1150 Feature fpet 532 535 regression issues
  src/main/steps/eligibility/start/content.test.ts
  src/main/steps/eligibility/start/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1150

#1154 Feature fpet 05 03 vunarabilities fix
  src/main/app/controller/PostController.ts
  src/main/app/nationality/NationalityGetController.ts
  src/main/steps/application/save-and-sign-out/get.ts
  src/main/steps/application/save-as-draft/SaveAsDraftGetController.ts
  src/main/steps/application/submitted/get.ts
  src/main/steps/application/timed-out/get.ts
  src/main/steps/children/find-family-court/FindFamilyCourtGetController.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtGetController.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.ts
  src/main/steps/children/social-worker/LocalAuthorityGetController.ts
  src/main/steps/sibling/relation/SiblingGetController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1154

#1083 Feature fpet 443 444
  src/main/assets/scss/task-list.scss
  src/main/steps/application/task-list/template.njk
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1083

#1171 Feature fpet 443 444
  src/main/assets/scss/task-list.scss
  src/main/steps/application/task-list/template.njk
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1171

#1178 removed functional tests
  Jenkinsfile_CNP
  charts/adoption-web/values.preview.template.yaml
  package.json
  src/test/e2e/tests/e2enegative_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1178

#1187 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1187

#1194 enble fortify in PR
  charts/adoption-web/values.preview.template.yaml
  src/main/modules/kba/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1194

#1190 FPET-563-added new local authority names
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1190
