Repository hmcts/adoption-web, pull requests merged in 2023-03, with the labels that each got.

#1023 ADOP-2222: LA - Birth Father Responsibility
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/birth-father/birthFatherSequence.test.ts
  src/main/steps/birth-father/birthFatherSequence.ts
  src/main/steps/birth-father/parental-responsibility/content.test.ts
  src/main/steps/birth-father/parental-responsibility/content.ts
  src/main/steps/birth-father/parental-responsibility/granted/content.test.ts
  src/main/steps/birth-father/parental-responsibility/granted/content.ts
  src/main/steps/birth-father/parental-responsibility/no-responsibility/content.test.ts
  src/main/steps/birth-father/parental-responsibility/no-responsibility/content.ts
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/urls.ts
  src/test/e2e/fixtures/caseData/childBirthFatherDetails.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1023

#1031 ADOP-2226-Update Sibling court order screen
  src/main/app/case/definition.ts
  src/main/steps/children/placement-order-summary/content.test.ts
  src/main/steps/children/placement-order-summary/content.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.test.ts
  src/main/steps/children/placement-order-summary/placement-order-summary.ts
  src/main/steps/children/placement-order-type/content.test.ts
  src/main/steps/children/placement-order-type/content.ts
  src/main/steps/children/remove-placement-order/content.ts
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.test.ts
  src/main/steps/sibling/placement-order-check-your-answers/content.ts
  src/main/steps/sibling/placement-order-type/content.test.ts
  src/main/steps/sibling/placement-order-type/content.ts
  src/main/steps/sibling/remove-placement-order/content.test.ts
  src/main/steps/sibling/remove-placement-order/content.ts
  src/main/steps/sibling/summary/content.test.ts
  src/main/steps/sibling/summary/content.ts
  src/main/steps/sibling/summary/placement-order-summary.test.ts
  src/main/steps/sibling/summary/placement-order-summary.ts
  src/test/e2e/pages/childDetailsPlacementOrder.page.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1031

#1037 ADOP-2096-Increased file size to 50 MB
  src/main/app/document/DocumentManagementClient.integration.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/steps/la-portal/upload-your-documents/content.test.ts
  src/main/steps/la-portal/upload-your-documents/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1037

#1034 Adop 2142 c UI eligibility timeout
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/assets/js/session-timeout.ts
  src/main/modules/oidc/index.ts
  src/main/steps/application/timed-out/content.ts
  src/main/steps/application/timed-out/get.test.ts
  src/main/steps/application/timed-out/get.ts
  src/main/steps/application/timed-out/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields/field-label.njk
  src/main/steps/la-portal/kba-case-ref/content.test.ts
  src/main/steps/la-portal/kba-case-ref/content.ts
  src/main/steps/urls.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1034

#1035 ADOP-2228: Multiple Children - Welsh Translation
  src/main/steps/applicant1/contact-details/content.test.ts
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/applicant2/contact-details/content.test.ts
  src/main/steps/applicant2/contact-details/content.ts
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/task-list/content.test.ts
  src/main/steps/application/task-list/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/eligibility/domicile/content.test.ts
  src/main/steps/eligibility/domicile/content.ts
  src/main/steps/eligibility/lived-uk/content.test.ts
  src/main/steps/eligibility/lived-uk/content.ts
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/eligibility/multiple-children-desc/content.test.ts
  src/main/steps/eligibility/multiple-children-desc/content.ts
  src/main/steps/eligibility/multiple-children/content.test.ts
  src/main/steps/eligibility/multiple-children/content.ts
  src/main/steps/eligibility/start/content.test.ts
  src/main/steps/eligibility/start/content.ts
  src/main/steps/eligibility/under-18/content.test.ts
  src/main/steps/eligibility/under-18/content.ts
  src/main/steps/eligibility/under-21/content.test.ts
  src/main/steps/eligibility/under-21/content.ts
  src/main/steps/la-portal/confirmation/content.test.ts
  src/main/steps/la-portal/confirmation/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.ts
  src/test/e2e/pages/login.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1035

#1041 ADOP-2122: CUI Changes - Accessibility Statement
  src/main/steps/application/accessibility-statement/content.test.ts
  src/main/steps/application/accessibility-statement/content.ts
  src/main/steps/application/accessibility-statement/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1041

#1043 ADOP-2208-Multiple Children - PCQ logics
  src/main/app/case/CaseApi.ts
  src/main/app/controller/PostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1043

#1052 ADOP-15: Welsh translation fixes
  src/main/steps/applicant1/other-names/content.test.ts
  src/main/steps/applicant1/other-names/content.ts
  src/main/steps/applicant2/other-names/content.test.ts
  src/main/steps/applicant2/other-names/content.ts
  src/main/steps/birth-father/nationality/content.test.ts
  src/main/steps/birth-father/nationality/content.ts
  src/main/steps/birth-mother/nationality/content.test.ts
  src/main/steps/birth-mother/nationality/content.ts
  src/main/steps/children/nationality/content.test.ts
  src/main/steps/children/nationality/content.ts
  src/main/steps/common/components/nationality.ts
  src/main/steps/common/components/other-names.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1052

#1044 ADOP-2251: LA - Other person parental responsibility questions
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/other-parent/otherParentSequence.test.ts
  src/main/steps/other-parent/otherParentSequence.ts
  src/main/steps/other-parent/parental-responsibility-granted/content.test.ts
  src/main/steps/other-parent/parental-responsibility-granted/content.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1044

#1048 ADOP-2207-MC-SaveDraft
  src/main/modules/csrf/index.ts
  src/main/modules/kba/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/application/save-as-draft/SaveAsDraftGetController.test.ts
  src/main/steps/application/save-as-draft/SaveAsDraftGetController.ts
  src/main/steps/application/save-as-draft/content.test.ts
  src/main/steps/application/save-as-draft/content.ts
  src/main/steps/application/save-as-draft/post.ts
  src/main/steps/application/save-as-draft/template.njk
  src/main/steps/la-portal/negative-scenario/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1048

#1024 ADOP-2119-AutoSuggest-Static-LA
  config/default.yaml
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/court/location.ts
  src/main/steps/children/applicant-social-worker/content.test.ts
  src/main/steps/children/applicant-social-worker/content.ts
  src/main/steps/children/applicant-social-worker/post.test.ts
  src/main/steps/children/applicant-social-worker/post.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.test.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.ts
  src/main/steps/children/social-worker/LocalAuthorityGetController.test.ts
  src/main/steps/children/social-worker/LocalAuthorityGetController.ts
  src/main/steps/children/social-worker/content.test.ts
  src/main/steps/children/social-worker/content.ts
  src/main/steps/children/social-worker/post.test.ts
  src/main/steps/children/social-worker/post.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields/hint.njk
  src/test/e2e/fixtures/caseData/applicantOrYourSocialWorkerDetails.js
  src/test/e2e/fixtures/caseData/childAdoptionAgencyDetails.js
  src/test/e2e/fixtures/caseData/childSocialWorkerDetails.js
  src/test/e2e/pages/checkYourAnswers.page.js
  src/test/e2e/pages/childAdoptionAgencyDetails.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1024

#1063 ADOP-2119-AutoSuggest-Static-LA
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  src/main/steps/children/social-worker/LocalAuthorityGetController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1063

#1059 ADOP-2292: Other Person - Content Change
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/other-parent/address-known/content.test.ts
  src/main/steps/other-parent/address-known/content.ts
  src/main/steps/other-parent/address/international/content.test.ts
  src/main/steps/other-parent/address/international/content.ts
  src/main/steps/other-parent/address/lookup/content.test.ts
  src/main/steps/other-parent/address/manual/content.test.ts
  src/main/steps/other-parent/address/manual/content.ts
  src/main/steps/other-parent/address/select/content.test.ts
  src/main/steps/other-parent/constants.ts
  src/main/steps/other-parent/exists/content.test.ts
  src/main/steps/other-parent/full-name/content.test.ts
  src/main/steps/other-parent/last-address-confirmed/content.test.ts
  src/main/steps/other-parent/last-address-confirmed/content.ts
  src/main/steps/other-parent/parental-responsibility-granted/content.test.ts
  src/main/steps/other-parent/served-with/content.test.ts
  src/main/steps/other-parent/served-with/content.ts
  src/test/e2e/pages/childOtherParentDetails.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1059

#1080 update chart version
  charts/adoption-web/Chart.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1080

#1086 updated node version in helm chart to fix helm issues
  charts/adoption-web/Chart.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1086

#1076 Updating the service url to platform.hmcts.net from .internal
  Jenkinsfile_CNP
  src/test/e2e/config.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1076

#1095 Update Terraform azurerm
  .nvmrc
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:adoption, prd:adoption, no-changes, rel:adoption-web-pr-1095
