Repository hmcts/adoption-web, pull requests merged in 2023-01, with the labels that each got.

#935 Fix nightly build failures for Adoption-web
  charts/adoption-web/values.preview.template.yaml
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-935

#924 FPET-232 Adoption - Start Page : added start page screen changes
  charts/adoption-web/values.preview.template.yaml
  src/main/steps/applicant1/applicant1Sequence.test.ts
  src/main/steps/applicant1/applicant1Sequence.ts
  src/main/steps/applicant1/start-placement/content.test.ts
  src/main/steps/applicant1/start-placement/content.ts
  src/main/steps/applicant1/start-placement/template.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/urls.ts
  src/test/config.ts
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/tests/smoke_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-924

#959 Release 1.1
  charts/adoption-web/values.preview.template.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-959

#958 ADOP-2053-Accessibility-NoVisibleLabel-Instructions
  src/main/steps/children/find-family-court/content.test.ts
  src/main/steps/children/find-family-court/content.ts
  src/main/steps/common/components/address-international.test.ts
  src/main/steps/common/components/address-international.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/address-manual.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-958

#953 ADOP-2057-Accessibility-InputPurpose-Usability
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/applicant2/contact-details/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-953

#943 ADOP-2044-Accessibility Testing - Dev - Non-Descriptive Names
  src/main/steps/common/common.content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-943

#955 ADOP-2045-Accessibility Testing - Dev - Focus Visible
  src/main/assets/scss/upload-documents.scss
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-955

#960 Added Error in page title
  src/main/steps/common/page.njk
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-960

#962 Feature adop 2049 brokenlink
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/steps/children/find-family-court/FindFamilyCourtPostController.test.ts
  src/main/steps/children/find-family-court/FindFamilyCourtPostController.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.test.ts
  src/main/steps/children/find-placement-order-court/FindPlacementOrderCourtPostController.ts
  src/main/steps/common/error/summary.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-962

#936 DAC Accessibility Fixes
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/assets/js/session-timeout.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/assets/scss/task-list.scss
  src/main/modules/i18n/index.test.ts
  src/main/modules/i18n/index.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant2/contact-details/content.ts
  src/main/steps/application/accessibility-statement/content.test.ts
  src/main/steps/application/accessibility-statement/content.ts
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/task-list/template.njk
  src/main/steps/birth-mother/occupation/content.test.ts
  src/main/steps/birth-mother/occupation/content.ts
  src/main/steps/children/placement-order-number/content.test.ts
  src/main/steps/children/placement-order-number/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/eligibility/domicile/content.test.ts
  src/main/steps/eligibility/domicile/content.ts
  src/main/steps/eligibility/lived-uk/content.test.ts
  src/main/steps/eligibility/lived-uk/content.ts
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/eligibility/start/template.njk
  src/main/steps/eligibility/under-18/content.test.ts
  src/main/steps/eligibility/under-18/content.ts
  src/main/steps/eligibility/under-21/content.test.ts
  src/main/steps/eligibility/under-21/content.ts
  src/main/steps/la-portal/upload-your-documents/template.njk
  src/test/steps/common.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-936

#964 Feature adop 2056 error message
  src/main/steps/birth-mother/address-known/content.test.ts
  src/main/steps/birth-mother/address-known/content.ts
  src/main/steps/children/sex-at-birth/content.test.ts
  src/main/steps/children/sex-at-birth/content.ts
  src/main/steps/eligibility/domicile/content.test.ts
  src/main/steps/eligibility/domicile/content.ts
  src/main/steps/eligibility/lived-uk/content.test.ts
  src/main/steps/eligibility/lived-uk/content.ts
  src/main/steps/eligibility/married/content.test.ts
  src/main/steps/eligibility/married/content.ts
  src/main/steps/eligibility/under-18/content.test.ts
  src/main/steps/eligibility/under-18/content.ts
  src/main/steps/eligibility/under-21/content.test.ts
  src/main/steps/eligibility/under-21/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-964

#961 ADOP-2042 Focus Order Part 1
  src/main/modules/helmet/index.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/common/page.njk
  src/main/steps/la-portal/upload-your-documents/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-961

#971 Vulnerability fix for cookiejar : CVE-2022-25901
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-971

#972 ADOP-1926 Fix for Task list status
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/la-portal/task-list/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-972

#973 ADOP-2051: Usability Fieldset Container
  src/main/steps/applicant1/address/confirm-change/content.test.ts
  src/main/steps/applicant1/address/confirm-change/content.ts
  src/main/steps/applicant1/address/confirm-change/template.njk
  src/main/steps/applicant2/address/confirm-change/content.test.ts
  src/main/steps/applicant2/address/confirm-change/content.ts
  src/main/steps/applicant2/address/confirm-change/template.njk
  src/main/steps/application/cookies/template.njk
  src/main/steps/common/form/form.njk
  src/main/steps/common/page.njk
  src/main/steps/common/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-973

#974 ADOP-1927-Delete Documents redirecting to Application submit page
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/main/modules/state-redirect/index.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-974
