Repository hmcts/adoption-web, pull requests merged in 2023-02, with the labels that each got.

#983 updated email address for liverpool court
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/adoption-web/values.yaml
  config/default.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-983

#978 ADOP-2148-SonarCodeCoverage
  package.json
  src/main/app/address/AddressLookupPostControllerBase.test.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/other-names/OtherNamesPostController.test.ts
  src/main/steps/applicant1/address/change/content.ts
  src/main/steps/applicant2/address/change/content.ts
  src/main/steps/application/save-as-draft/content.test.ts
  src/main/steps/birth-father/address-known/content.ts
  src/main/steps/birth-father/alive/content.test.ts
  src/main/steps/birth-father/last-address-confirmed/content.ts
  src/main/steps/birth-father/occupation/content.ts
  src/main/steps/birth-mother/address-known/content.ts
  src/main/steps/birth-mother/last-address-confirmed/content.ts
  src/main/steps/birth-mother/occupation/content.ts
  src/main/steps/birth-mother/still-alive/content.test.ts
  src/main/steps/children/adoption-agency/content.ts
  src/main/steps/children/local-authority/content.test.ts
  src/main/steps/children/other-adoption-agency/content.test.ts
  src/main/steps/children/placement-order-number/content.test.ts
  src/main/steps/children/placement-order-type/content.test.ts
  src/main/steps/children/placement-order/PlacementOrderGetController.test.ts
  src/main/steps/children/placement-order/PlacementOrderPostController.test.ts
  src/main/steps/children/social-worker/content.test.ts
  src/main/steps/la-portal/kba-case-ref/content.test.ts
  src/main/steps/other-parent/address-known/content.ts
  src/main/steps/other-parent/exists/content.ts
  src/main/steps/other-parent/last-address-confirmed/content.ts
  src/main/steps/sibling/exists/content.ts
  src/main/steps/sibling/placement-order-type/content.test.ts
  src/main/steps/sibling/placement-order/post.test.ts
  src/main/steps/sibling/relation/content.test.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-978

#984 ADOP-2176-RegressionDefect
  src/main/steps/la-portal/task-list/utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-984

#985 ADOP-2178: Task list and review answer content changes
  src/main/steps/application/task-list/content.test.ts
  src/main/steps/application/task-list/content.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/test/e2e/fixtures/caseData/checkYourAnswersPageKeysDetails.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-985

#986 ADOP 2179: Application submitted/confirmation page content changes
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/submitted/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-986

#990 ADOP-2157-LA-URChanges
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/la-portal/task-list/content.test.ts
  src/main/steps/la-portal/task-list/content.ts
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/taskList.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-990

#988 ADOP-2052-Accessibility Testing - Non-Descriptive Links
  src/main/steps/application/task-list/content.test.ts
  src/main/steps/application/task-list/content.ts
  src/main/steps/application/task-list/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-988

#989 ADOP-2124: CUI Changes - UR Changes
  src/main/steps/applicant1/contact-details/content.test.ts
  src/main/steps/applicant1/contact-details/content.ts
  src/main/steps/applicant2/contact-details/content.test.ts
  src/main/steps/applicant2/contact-details/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-989

#963 ADOP-2054-AccessibilityTesting-Timeout
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/assets/js/session-timeout.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/timeout-modal.scss
  src/main/steps/application/applicationSequence.test.ts
  src/main/steps/application/applicationSequence.ts
  src/main/steps/application/save-and-relogin/content.test.ts
  src/main/steps/application/save-and-relogin/content.ts
  src/main/steps/application/save-and-relogin/post.test.ts
  src/main/steps/application/save-and-relogin/post.ts
  src/main/steps/application/save-and-relogin/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/common/timeout-dialog.njk
  src/main/steps/urls.ts
  src/test/e2e/pages/saveAsDraft.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-963

#997 ADOP-2169: CUI - Pay and submit page - Part 1
  src/main/steps/review-pay-submit/pay-and-submit/content.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.ts
  src/main/steps/review-pay-submit/pay-and-submit/template.njk
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.test.ts
  src/main/steps/review-pay-submit/reviewPaySubmitSequence.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/tests/e2enegative_test.js
  src/test/e2e/tests/saveAsDraft_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-997

#987 ADOP-2175 multiple children changes
  charts/adoption-web/Chart.yaml
  src/main/app/controller/AppRequest.ts
  src/main/steps/eligibility/eligibilitySequence.test.ts
  src/main/steps/eligibility/eligibilitySequence.ts
  src/main/steps/eligibility/multiple-children-desc/content.test.ts
  src/main/steps/eligibility/multiple-children-desc/content.ts
  src/main/steps/eligibility/multiple-children-desc/post.ts
  src/main/steps/eligibility/multiple-children-desc/template.njk
  src/main/steps/eligibility/multiple-children/content.test.ts
  src/main/steps/eligibility/multiple-children/content.ts
  src/main/steps/eligibility/multiple-children/post.ts
  src/main/steps/eligibility/start/template.njk
  src/main/steps/index.test.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/login.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-987

#1001 ADOP-2186-Case reference generation logic to move from IDAM login page to 'Apply with' page submission.
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/controller/PostController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/application/home/get.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1001

#1003 ADOP-2196-Multiple Children - Eligibility screen redirection logic
  src/main/steps/eligibility/EligibilityPostController.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1003

#1004 Adop 2154 accessibility testing timeout
  src/main/assets/js/session-timeout.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/application/save-and-relogin/post.ts
  src/main/steps/application/timed-out/get.test.ts
  src/main/steps/application/timed-out/get.ts
  src/main/steps/application/timed-out/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1004

#1002 ADOP-2155: LA portal - Content changes
  src/main/steps/la-portal/confirmation/content.test.ts
  src/main/steps/la-portal/confirmation/content.ts
  src/main/steps/la-portal/confirmation/template.njk
  src/main/steps/la-portal/start-page/content.test.ts
  src/main/steps/la-portal/start-page/content.ts
  src/main/steps/la-portal/start-page/template.njk
  src/main/steps/la-portal/upload-your-documents/content.test.ts
  src/main/steps/la-portal/upload-your-documents/content.ts
  src/main/steps/la-portal/upload-your-documents/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1002

#994 Adop 2172 reasonable adjustment cya
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/applicant1Sequence.test.ts
  src/main/steps/applicant1/applicant1Sequence.ts
  src/main/steps/applicant1/extra-support/content.test.ts
  src/main/steps/applicant1/extra-support/content.ts
  src/main/steps/applicant1/extra-support/template.njk
  src/main/steps/applicant2/applicant2Sequence.test.ts
  src/main/steps/applicant2/applicant2Sequence.ts
  src/main/steps/applicant2/extra-support/content.test.ts
  src/main/steps/applicant2/extra-support/content.ts
  src/main/steps/applicant2/extra-support/template.njk
  src/main/steps/application/task-list/utils.test.ts
  src/main/steps/application/task-list/utils.ts
  src/main/steps/review-pay-submit/check-your-answers/content.test.ts
  src/main/steps/review-pay-submit/check-your-answers/content.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
  src/main/steps/urls.ts
  src/test/e2e/fixtures/caseData/checkYourAnswersPageKeysDetails.js
  src/test/e2e/fixtures/caseData/extraSupportDetails.js
  src/test/e2e/fixtures/caseData/primaryApplicantPersonalDetails.js
  src/test/e2e/fixtures/caseData/secondApplicantPersonalDetails.js
  src/test/e2e/pages/checkYourAnswers.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/e2e/pages/primaryApplicantPersonalDetails.page.js
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/e2e/tests/checkYourAnswers_test.js
  src/test/e2e/tests/e2enegative_test.js
  src/test/e2e/tests/saveAsDraft_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-994

#1007 Adop 2198 mc ida mlogin redirects
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/controller/PostController.ts
  src/main/steps/application/home/get.ts
  src/main/steps/eligibility/EligibilityPostController.ts
  src/test/e2e/tests/submitAdoptionApplication_test.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1007

#1026 ADOP-2118-Served option to be provided to recipients
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/birth-father/served-with/content.test.ts
  src/main/steps/birth-father/served-with/content.ts
  src/main/steps/birth-mother/served-with/content.test.ts
  src/main/steps/birth-mother/served-with/content.ts
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/la-portal/laPortalSequence.test.ts
  src/main/steps/la-portal/laPortalSequence.ts
  src/main/steps/la-portal/task-list/utils.test.ts
  src/main/steps/la-portal/task-list/utils.ts
  src/main/steps/other-parent/served-with/content.test.ts
  src/main/steps/other-parent/served-with/content.ts
  src/main/steps/urls.ts
  src/test/e2e/fixtures/caseData/checkYourAnswersPageKeysDetails.js
  src/test/e2e/fixtures/caseData/childBirthFatherDetails.js
  src/test/e2e/fixtures/caseData/childBirthMothersDetails.js
  src/test/e2e/fixtures/caseData/childOtherParentDetails.js
  src/test/e2e/pages/childBirthFatherDetails.page.js
  src/test/e2e/pages/childBirthMothersDetails.page.js
  src/test/e2e/pages/childOtherParentDetails.page.js
  src/test/e2e/pages/laCheckYourAnswers.page.js
  src/test/e2e/pages/otherApplicantPersonalDetails.page.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1026

#1013 ADOP-2229: LA Start Page Content Change
  src/main/steps/la-portal/start-page/content.test.ts
  src/main/steps/la-portal/start-page/content.ts
  src/main/steps/la-portal/start-page/template.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1013

#1011 ADOP-2121: LA & CUI - Contact Us changes
  Jenkinsfile_CNP
  codecept.conf.js
  src/main/steps/applicant1/extra-support/template.njk
  src/main/steps/applicant2/extra-support/template.njk
  src/main/steps/application/contact-us/content.test.ts
  src/main/steps/application/contact-us/content.ts
  src/main/steps/application/contact-us/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/contactForHelp.njk
  src/test/config.ts
  src/test/e2e/pages/childsDetails.page.js
  src/test/e2e/pages/login.page.js
  src/test/e2e/pages/taskList.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1011

#1014 Adop 2181 mc confirm and email logic
  src/main/app/case/CaseApi.ts
  src/main/app/case/NewCaseRedirectController.ts
  src/main/app/controller/PostController.ts
  src/main/routes.ts
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/submitted/template.njk
  src/main/steps/eligibility/EligibilityPostController.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/reviewPayAndSubmit.page.js
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1014
