Repository hmcts/adoption-web, pull requests merged in 2024-09, with the labels that each got.

#1576 ADOP-2522: Bump axios, add now required typings to responses
  package.json
  playwright-e2e/helpers/idamTestApiHelpers.ts
  src/main/app/case/CaseApi.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1576

#1580 [ADOP-2529] Use CDAM instead of Docstore
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementClient.integration.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1580

#1582 Adop 2533 - new e2e citizen journey test coverage
  playwright-e2e/pages/numberOfApplicants.page.ts
  playwright-e2e/tests/submit-application-journey.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1582
