Repository hmcts/adoption-web, pull requests merged in 2024-06, with the labels that each got.

#1547 Adop 2301 update contact
  src/main/steps/application/accessibility-statement/content.test.ts
  src/main/steps/application/accessibility-statement/content.ts
  src/main/steps/application/accessibility-statement/template.njk
  src/main/steps/application/contact-us/content.test.ts
  src/main/steps/application/contact-us/content.ts
  src/main/steps/application/contact-us/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/contactForHelp.njk
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1547

#1553 [ADOP-2425] adding ITHC back into branchesToSync
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1553

#1555 ADOP-2475 Content Changes to Applicant Name Screens
  src/main/steps/applicant1/full-name/content.test.ts
  src/main/steps/applicant1/full-name/content.ts
  src/main/steps/applicant1/full-name/form.njk
  src/main/steps/applicant1/full-name/template.njk
  src/main/steps/applicant2/full-name/content.test.ts
  src/main/steps/applicant2/full-name/content.ts
  src/main/steps/applicant2/full-name/form.njk
  src/main/steps/applicant2/full-name/template.njk
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1555

#1556 [ADOP-2469] Add AAT Dynatrace script to cookie banner
  src/main/steps/common/cookie-banner.njk
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1556
