Repository hmcts/adoption-web, pull requests merged in 2024-12, with the labels that each got.

#1604 ADOP-2548: Full Citizen and LA Journey
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/fixtures/fixtures.ts
  playwright-e2e/page-objects/citizen/payments/citSubmittedPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-certificate/laChildNationalityPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-certificate/laChildSexAtBirthPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherLastDateConfirmedAddressPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherLastKnownAddressBranchPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherNamePage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherNationalityPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherOccupationPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherOnCertificatePage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherParentalResponsibilityGrantedPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherParentalResponsibilityPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherServeDocumentsPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/laBirthFatherStillAliveStatusPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-father/lsBirthFatherLastKnownAddressPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherAliveStatusPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherLastDateConfirmedAddressPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherLastKnownAddressBranchPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherLastKnownAddressPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherNamePage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherNationalityPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherOccupationPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherServeDocumentsPage.page.ts
  playwright-e2e/page-objects/local-authority/document-upload/laUploadDocuments.page.ts
  playwright-e2e/page-objects/local-authority/laCheckYourAnswer.page.ts
  playwright-e2e/page-objects/local-authority/laChildDetailsPage.page.ts
  playwright-e2e/page-objects/local-authority/laConfirmationPage.page.ts
  playwright-e2e/page-objects/local-authority/laGettingStartedPage.page.ts
  playwright-e2e/page-objects/local-authority/laSignInPage.page.ts
  playwright-e2e/page-objects/local-authority/laStatementOfTruth.page.ts
  playwright-e2e/page-objects/local-authority/other-person/laOtherPersonResponsibilityPage.page.ts
  playwright-e2e/page-objects/local-authority/placement/laPlacementAndCourtsSection.page.ts
  playwright-e2e/page-objects/local-authority/placement/laPlacementDateOfOrderPage.page.ts
  playwright-e2e/page-objects/local-authority/placement/laPlacementOrderNumberPage.page.ts
  playwright-e2e/page-objects/local-authority/placement/laPlacementOrdersSummaryPage.page.ts
  playwright-e2e/page-objects/local-authority/siblings/laSiblingCourtDetailsSection.page.ts
  playwright-e2e/pages/basePage.page.ts
  playwright-e2e/pages/nationality.page.ts
  playwright-e2e/pages/signInPage.page.ts
  playwright-e2e/tests/full_journey/e2e-citizen-la-journey-tests.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1604

#1614 Update nanoid to >=3.3.8 (vulnerability fix)
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1614

#1594 ADOP-2448: Fix applying-with page
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/CaseApi.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1594
