Repository hmcts/adoption-web, pull requests merged in 2024-03, with the labels that each got.

#1497 Fix fortify
  broker-compose.yaml
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1497

#1498 Fix fortify
  broker-compose.yaml
  config/custom-environment-variables.yaml
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1498

#1499 ADOP_2365_Content_Update
  src/main/steps/application/privacy-policy/content.test.ts
  src/main/steps/application/privacy-policy/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1499

#1500 Fix fortify
  config/default.yaml
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1500

#1502 ADOP_2392_AddNewLA
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1502
