Repository hmcts/adoption-web, pull requests merged in 2024-11, with the labels that each got.

#1598 Suppress zapscan
  audit.json
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1598

#1600 Fix cookie banner script - `prod` not `production`
  src/main/steps/common/cookie-banner.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1600

#1593 [ADOP-2442] Display Birth Father's details if identity known
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
  src/main/steps/la-portal/check-your-answers/utils.test.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1593

#1597 [ADOP-2572] Fix LA SOT Timeout Bug
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1597

#1573 ADOP-2503: update readme file
  README.md
  playwright-e2e/README.md
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1573

#1603 ADOP-2536: Welsh wording change on content.ts
  src/main/steps/la-portal/check-your-answers/content.test.ts
  src/main/steps/la-portal/check-your-answers/content.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1603

#1595 [ADOP-2408] remove redundant HPA config from charts (moved to cnp-flux)
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.aat.template.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1595

#1605 [ADOP-2408] adding dev memory and cpu values back into AAT chart
  charts/adoption-web/values.aat.template.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1605
