Repository hmcts/adoption-web, pull requests merged in 2024-07, with the labels that each got.

#1552 ADOP-2479: replace auth token with azure secret
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  config/custom-environment-variables.yaml
  config/test.yaml
  package.json
  src/main/app/case/case.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/court/court-venues-api.ts
  src/main/steps/children/social-worker/LocalAuthorityGetController.ts
  src/test/e2e/tests/checkYourAnswers_test.js
  src/test/e2e/tests/saveAsDraft_test.js
  src/test/e2e/tests/submitAdoptionApplication_test.js
  src/test/unit/utils/mockRequest.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1552

#1558 Adop 2461 new
  .gitignore
  README.md
  config/custom-environment-variables.yaml
  package.json
  playwright-e2e/helpers/accessibilityHelper.ts
  playwright-e2e/helpers/idamTestApiHelpers.ts
  playwright-e2e/hooks/createDeleteUser.hook.ts
  playwright-e2e/pages/adoptionAgency.page.ts
  playwright-e2e/pages/app.page.ts
  playwright-e2e/pages/applicantsDetails.page.ts
  playwright-e2e/pages/base-page.ts
  playwright-e2e/pages/basePage.page.ts
  playwright-e2e/pages/childDetails.page.ts
  playwright-e2e/pages/contactDetails.page.ts
  playwright-e2e/pages/dateChildMoved.page.ts
  playwright-e2e/pages/eligibility.page.ts
  playwright-e2e/pages/extraSupport.page.ts
  playwright-e2e/pages/familyCourtDetails.page.ts
  playwright-e2e/pages/numberOfApplicants.page.ts
  playwright-e2e/pages/pcq.page.ts
  playwright-e2e/pages/reviewSubmit.page.ts
  playwright-e2e/pages/signInPage.page.ts
  playwright-e2e/pages/taskList.page.ts
  playwright-e2e/tests/eligibility-tests.spec.ts
  playwright-e2e/tests/submit-application-journey.spec.ts
  playwright.config.ts
  src/main/app/case/case.ts
  src/main/app/controller/PostController.test.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1558

#1570 ADOP: Add secret idam access token
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  playwright-e2e/helpers/idamTestApiHelpers.ts
  playwright-e2e/hooks/createDeleteUser.hook.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1570

#1571 ADOP-2402: add accessibility scan, samsung device and improve report to e2e test
  Jenkinsfile_nightly
  package.json
  playwright-e2e/helpers/accessibilityHelper.ts
  playwright-e2e/tests/submit-application-journey.spec.ts
  playwright.config.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1571

#1572 ADOP-2502: fortify failure in e2e test fix
  playwright-e2e/hooks/createDeleteUser.hook.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1572

#1574 ADOP-2505: Improve playwright smoke test
  playwright-e2e/pages/app.page.ts
  playwright-e2e/pages/applicantsDetails.page.ts
  playwright-e2e/pages/childDetails.page.ts
  playwright-e2e/pages/dateChildMoved.page.ts
  playwright-e2e/pages/numberOfApplicants.page.ts
  playwright-e2e/pages/reviewSubmit.page.ts
  playwright-e2e/pages/taskList.page.ts
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/tests/submit-application-journey.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1574
