Repository hmcts/adoption-web, pull requests merged in 2024-10, with the labels that each got.

#1588 vulnerability fix
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1588

#1586 ADOP-2534 refactored user journey
  playwright-e2e/helpers/e2eJourneyHelper.ts
  playwright-e2e/tests/submit-application-journey.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1586

#1587 ADOP-2523 Escaping characters to prevent HTML injection
  src/main/app/case/case.ts
  src/main/app/case/formatter/address.test.ts
  src/main/app/case/formatter/address.ts
  src/main/steps/applicant2/same-address/content.ts
  src/main/steps/common/functions/sanitize.test.ts
  src/main/steps/common/functions/sanitize.ts
  src/main/steps/la-portal/check-your-answers/utils.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.test.ts
  src/main/steps/review-pay-submit/check-your-answers/utils.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1587

#1592 [ADOP-2514] Add Dynatrace RUM for production
  src/main/steps/common/cookie-banner.njk
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1592
