Repository hmcts/adoption-web, pull requests merged in 2024-04, with the labels that each got.

#1506 ADOP_2308_Spacing_Issue
  src/main/modules/kba/index.ts
  src/main/steps/children/full-name/content.ts
  src/main/steps/la-portal/kba-case-ref/content.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1506

#1512 ADOP-2403 Setup playwright framework for adoption-web
  .gitignore
  Jenkinsfile_nightly
  package.json
  playwright-e2e/settings/urls.ts
  playwright-e2e/smoke.spec.ts
  playwright.config.ts
  test-results/result.xml
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1512

#1517 [ADOP-2323] temporarily removed ITHC from branchesToSync
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1517

#1521 ADOP-update-nodejs-healthcheck: Updated to 1.8.4 to resolve CVE
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1521

#1509 Adop 2376 fee increase
  README.md
  charts/adoption-web/values.preview.template.yaml
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/submitted/get.test.ts
  src/main/steps/application/submitted/getSubmittedController.test.ts
  src/main/steps/application/submitted/getSubmittedController.ts
  src/main/steps/eligibility/multiple-children-desc/content.test.ts
  src/main/steps/eligibility/multiple-children-desc/content.ts
  src/main/steps/eligibility/multiple-children-desc/getMultipleChildrenDescController.test.ts
  src/main/steps/eligibility/multiple-children-desc/getMultipleChildrenDescController.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.ts
  src/main/steps/review-pay-submit/pay-and-submit/getPayAndSubmitController.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/getPayAndSubmitController.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1509

#1523 ADOP-2376-restore-preview-aat
  charts/adoption-web/values.preview.template.yaml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1523

#1508 PR testing redis rdb on ITHC
  Jenkinsfile_CNP
  README.md
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  src/main/steps/application/submitted/content.test.ts
  src/main/steps/application/submitted/content.ts
  src/main/steps/application/submitted/get.test.ts
  src/main/steps/application/submitted/getSubmittedController.test.ts
  src/main/steps/application/submitted/getSubmittedController.ts
  src/main/steps/eligibility/multiple-children-desc/content.test.ts
  src/main/steps/eligibility/multiple-children-desc/content.ts
  src/main/steps/eligibility/multiple-children-desc/getMultipleChildrenDescController.test.ts
  src/main/steps/eligibility/multiple-children-desc/getMultipleChildrenDescController.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.ts
  src/main/steps/review-pay-submit/pay-and-submit/getPayAndSubmitController.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/getPayAndSubmitController.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, aat/add-or-update, rel:adoption-web-pr-1508

#1522 ADOP-2432 - Enhance - Add Citizen eligibility tests in Playwright
  playwright-e2e/README.md
  playwright-e2e/fixtures/fixtures.ts
  playwright-e2e/pages/eligibility-pages.ts
  playwright-e2e/tests/eligibility-one-child.spec.ts
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/utils/axe-test.ts
  playwright-e2e/utils/urls.ts
  playwright.config.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1522
