Repository hmcts/adoption-web, pull requests merged in 2024-02, with the labels that each got.

#1491 tech-debt/clean-eligibility-start: Custom get controller no longer needed as Fee value not dynamically rendered
  src/main/steps/eligibility/start/EligibilityStartGetController.test.ts
  src/main/steps/eligibility/start/EligibilityStartGetController.ts
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1491

#1492 Updated README to reflect current steps to run service locally
  README.md
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1492

#1493 Adop 2327 2333 express nunjucks
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1493

#1494 Adop 2299 - Update crown logo
  package.json
  src/main/assets/scss/main.scss
  src/main/steps/common/page.njk
  yarn.lock
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1494

#1495 ADOP-2299-Axios: Address vulnerability with ADOP-2332
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1495
