Repository hmcts/adoption-web, pull requests merged in 2025-03, with the labels that each got.

#1632 ADOP-2622 - Child DoB e2e tests
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/applying/citApplyingWithPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildDoBPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherAliveStatusPage.page.ts
  playwright-e2e/tests/citizen_journey/child-details/child-dob-tests.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1632

#1630 ADOP-2617 - Name of Child e2e tests
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/applying/citApplyingWithPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildDoBPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildFullNameAfterAdoptionPage.page.ts
  playwright-e2e/page-objects/citizen/payments/citSubmittedPage.page.ts
  playwright-e2e/tests/citizen_journey/child-details/child-dob-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-after-adoption-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-tests.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1630

#1651 bump axios
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1651

#1631 ADOP-2608 Child details e2e tests
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/applying/citApplyingWithPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildDoBPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildFullNameAfterAdoptionPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildFullNamePage.page.ts
  playwright-e2e/page-objects/citizen/save-as-draft/citSaveAsDraftPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherAliveStatusPage.page.ts
  playwright-e2e/tests/citizen_journey/child-details/child-dob-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-after-adoption-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-tests.spec.ts
  playwright-e2e/tests/citizen_journey/test-utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1631

#1657 Remove dependabot as we have renovate
  .github/dependabot.yml
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1657

#1659 Caching tokens/managing test user improvements
  playwright-e2e/helpers/idamTestApiHelpers.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1659

#1647 Origin/ho sea0051 readme updates
  README.md
  package.json
  playwright-e2e/README.md
Labels: ns:adoption, prd:adoption, enable_fortify_scan, rel:adoption-web-pr-1647

#1661 pipeline-fix-19032025
  playwright-e2e/page-objects/citizen/child-details/citChildDoBPage.page.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1661

#1662 ADOP 2625 - ENV setup
  Jenkinsfile_nightly
  package.json
  playwright-e2e/README.md
  playwright-e2e/pages/signInPage.page.ts
  playwright-e2e/scripts/get_secrets.sh
  playwright-e2e/tests/citizen_journey/applying-with-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-dob-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-after-adoption-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-tests.spec.ts
  playwright-e2e/tests/citizen_journey/date-child-moved-in-tests.spec.ts
  playwright-e2e/tests/citizen_journey/task-list-tests.spec.ts
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/utils/urls.ts
  playwright.config.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1662

#1660 ADOP-2640 Remove Pa11y
  Jenkinsfile_CNP
  README.md
  jest.a11y.config.js
  package.json
  src/test/a11y/a11y.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1660

#1663 Revert "ADOP-2640 Remove Pa11y (#1660)"
  Jenkinsfile_CNP
  README.md
  jest.a11y.config.js
  package.json
  src/test/a11y/a11y.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1663
