Repository hmcts/adoption-web, pull requests merged in 2025-04, with the labels that each got.

#1665 ADOP-2647 Pa11y Removed
  Jenkinsfile_CNP
  package.json
  playwright-e2e/pages/signInPage.page.ts
  playwright-e2e/tests/citizen_journey/applying-with-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-dob-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-after-adoption-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-tests.spec.ts
  playwright-e2e/tests/citizen_journey/date-child-moved-in-tests.spec.ts
  playwright-e2e/tests/citizen_journey/task-list-tests.spec.ts
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/utils/urls.ts
  src/test/a11y/a11y.ts
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1665

#1671 ADOP-2647 Master pipeline smoke test fix SCOUTING
  package.json
Labels: ns:adoption, prd:adoption

#1674 ADOP-2647: PCQ env variable added
  Jenkinsfile_CNP
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/utils/toggles.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1674

#1675 ADOP-2647 - env variable type changes
  Jenkinsfile_CNP
  playwright-e2e/utils/toggles.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1675

#1664 ADOP-2641 Update Fees to 207 version 4 (deadline 7/04/2025)
  src/main/steps/review-pay-submit/payment/payment-callback/get.test.ts
  src/test/api/fee-register.api.test.ts
  src/test/e2e/pages/reviewPayAndSubmit.page.js
  src/test/pact/fees-register-api.test.ts
  src/test/pact/payment-api.test.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1664

#1676 [ADOP-2641] update fee version to 5
  src/test/api/fee-register.api.test.ts
  src/test/pact/fees-register-api.test.ts
  src/test/pact/payment-api.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1676

#1683 ADOP-2648 fix
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1683

#1684 ADOP-2648: master fix
  Jenkinsfile_CNP
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1684

#1686 ADOP-2648: master pipeline fix
  Jenkinsfile_CNP
  package.json
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1686

#1667 ADOP-2627 Child Social Details e2e tests
  package.json
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/adoption-agency-and-social-worker/citChildSocialWorkerDetailsPage.page.ts
  playwright-e2e/page-objects/citizen/applying/citApplyingWithPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildDoBPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildFullNameAfterAdoptionPage.page.ts
  playwright-e2e/page-objects/citizen/child-details/citChildFullNamePage.page.ts
  playwright-e2e/tests/citizen_journey/adoption-agency-and-social-worker/child-social-worker-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-dob-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-after-adoption-tests.spec.ts
  playwright-e2e/tests/citizen_journey/child-details/child-name-tests.spec.ts
  playwright-e2e/tests/citizen_journey/date-child-moved-in-tests.spec.ts
  playwright-e2e/tests/citizen_journey/task-list-tests.spec.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1667
