Repository hmcts/adoption-web, pull requests merged in 2025-06, with the labels that each got.

#1690 ADOP-2487 Add Banner for scheduled maintenance notifications
  Jenkinsfile_nightly
  charts/adoption-web/Chart.yaml
  charts/adoption-web/values.preview.template.yaml
  charts/adoption-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  playwright-e2e/components/banner.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/eligibility/start.page.ts
  playwright-e2e/pages/basePage.page.ts
  playwright-e2e/tests/full_journey/e2e-citizen-la-journey-tests.spec.ts
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/utils/config.utils.ts
  playwright-e2e/utils/toggles.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/notification-banner.njk
  src/main/steps/common/page.njk
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1690

#1694 Update README to improve steps to run locally
  README.md
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1694

#1698 ADOP-2685 temporarily suppressing low CVE-2025-5889
  yarn-audit-known-issues
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1698

#1693 DO NOT MERGE | [ADOP-2679] Applicant with Multiple Draft/Awaiting Payment Cases Fix
  src/main/app/case/CaseApi.integration.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/controller/PostController.test.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1693

#1696 ADOP-2670: Swap to Azure Artefacts from JitPack for Dep consuming
  test/java/build.gradle
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1696

#1700 ADOP-2670-2: Update JVM to use Java 17 and Fortify use artifacts version
  test/java/build.gradle
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1700
