Repository hmcts/adoption-web, pull requests merged in 2025-02, with the labels that each got.

#1633 Update playwright to 1.50
  package.json
  yarn.lock
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1633

#1634 removed samsung emulations
  package.json
  playwright.config.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1634

#1636 Use --with-deps flags with playwright install
  package.json
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1636
