Repository hmcts/adoption-web, pull requests merged in 2025-01, with the labels that each got.

#1610 ADOP-2559 Improve wording so Citizens expect Adoption application-submitted page and confirmation email
  src/main/steps/review-pay-submit/pay-and-submit/content.test.ts
  src/main/steps/review-pay-submit/pay-and-submit/content.ts
  src/main/steps/review-pay-submit/pay-and-submit/template.njk
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1610

#1617 [ADOP-2579] Move Dynatrace RUM to page head
  src/main/steps/common/cookie-banner.njk
  src/main/steps/common/page.njk
Labels: ns:adoption, prd:adoption, enable_keep_helm, rel:adoption-web-pr-1617

#1626 [ADOP-2575] Update Terraform and the azurerm provider to latest versions
  Jenkinsfile_CNP
  infrastructure/.terraform-version
  infrastructure/state.tf
Labels: ns:adoption, prd:adoption, aat/add-or-update, prod/add-or-update, rel:adoption-web-pr-1626

#1622 [ADOP-2600] Redirect citizen to application_submitted when case state=LaSubmitted
  src/main/steps/application/home/get.test.ts
  src/main/steps/application/home/get.ts
  src/main/steps/application/submitted/getSubmittedController.ts
Labels: ns:adoption, prd:adoption, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:adoption-web-pr-1622

#1611 ADOP-2601 Citzen ApplyWith page e2e tests
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/applying/citApplyingWithPage.page.ts
  playwright-e2e/page-objects/local-authority/birth-mother/laBirthMotherAliveStatusPage.page.ts
  playwright-e2e/pages/basePage.page.ts
  playwright-e2e/tests/citizen_journey/applying-with-tests.spec.ts
  playwright-e2e/tests/full_journey/e2e-citizen-la-journey-tests.spec.ts
  playwright-e2e/tests/smoke.spec.ts
  playwright-e2e/utils/config.utils.ts
Labels: ns:adoption, prd:adoption, rel:adoption-web-pr-1611

#1629 ADOP-2618 - e2e test coverage fixes
  playwright-e2e/page-objects/citizen/payments/citSubmittedPage.page.ts
  playwright-e2e/tests/full_journey/e2e-citizen-la-journey-tests.spec.ts
Labels: ns:adoption, prd:adoption

#1619 ADOP-2604 task-list e2e test case coverage
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/page-objects/citizen/applying/citApplyingWithPage.page.ts
  playwright-e2e/page-objects/citizen/payments/citSubmittedPage.page.ts
  playwright-e2e/page-objects/citizen/task-list/citTaskListPage.page.ts
  playwright-e2e/pages/basePage.page.ts
  playwright-e2e/tests/citizen_journey/task-list-tests.spec.ts
Labels: ns:adoption, prd:adoption
